### ISSUE TITLE
adding value to options

### ISSUE THREAD

**Issue by Avi-ADAM** [janosh/svelte-multiselect#1]

**Comment by janosh** [comment]
You mean turn `options` into an array of objects like

```js
const options = [
  { value: 42, label: 'Foo' },
  { value: 43, label: 'Bar' },
]
```

instead of an array of literals (i.e. strings or ints) like `const options = ['Foo', 'Bar']`?

**Comment by Avi-ADAM** [comment]
how should i call it option={options.label} is not working and i get eather error of "Unexpected token "."" or get it as "object object" instead of the label string.

**Comment by janosh** [comment]
Could you share your full code here?

**Comment by Avi-ADAM** [comment]
<script>

import MultiSelect from 'svelte-multiselect'

const country =  [
                { value: 17, label: 'Åland Islands'},
                { value: 18, label: 'Afghanistan'},
                { value: 19, label: 'Albania'},
                { value: 20, label: 'Algeria'},
                { value: 21, label: 'American Samoa'},
                { value: 22, label: 'Andorra'},
                { value: 23, label: 'Angola'},
                { value: 24, label: 'Anguilla'},
                { value: 25, label: 'Antarctica'},
                { value: 26, label: 'Antigua and Barbuda'},
                { value: 27, label: 'Argentina'},
                { value: 28, label: 'Armenia'},
                { value: 29, label: 'Aruba'},
                { value: 30, label: 'Australia'},
                { value: 31, label: 'Austria'},
                { value: 32, label: 'Azerbaijan'},
                { value: 33, label: 'Bahamas'},
                { value: 34, label: 'Bahrain'},
                { value: 35, label: 'Bangladesh'},
                { value: 36, label: 'Barbados'},
                { value: 37, label: 'Belarus'},
                { value: 38, label: 'Belgium'},
                { value: 40, label: 'Belize'},
                { value: 41, label: 'Benin'},
                { value: 42, label: 'Bermuda'},
                { value: 43, label: 'Bhutan'},
                { value: 44, label: 'Bolivia'},
                { value: 45, label: 'Bonaire, Sint Eustatius and Saba'},
                { value: 46, label: 'Bosnia and Herzegovina'},
                { value: 47, label: 'Botswana'},
                { value: 48, label: 'Bouvet Island'},
                { value: 49, label: 'Brazil'},
                { value: 50, label: 'British Indian Ocean Territory'},
                { value: 51, label: 'Brunei Darussalam'},
                { value: 52, label: 'Bulgaria'},
                { value: 53, label: 'Burkina Faso</'}, 
                { value: 54, label: 'Burundi</'}, 
                { value: 55, label: 'Cambodia</'}, 
                { value: 56, label: 'Cameroon</'}, 
                { value: 57, label: 'Canada</'}, 
                { value: 58, label: 'Cape Verde</'}, 
                { value: 59, label: 'Cayman Islands'}, 
                { value: 60, label: 'Central African Republic'},
                { value: 61, label: 'Chad'},
                { value: 62, label: 'Chile'},
                { value: 63, label: 'China'},
                { value: 64, label: 'Christmas Island'},
                { value: 65, label: 'Cocos (Keeling) Islands'},
                { value: 66, label: 'Colombia'},
                { value: 67, label: 'Comoros'},
                { value: 68, label: 'Congo'},
                { value: 69, label: 'Congo, The Democratic Republic of The'},
                { value: 70, label: 'Cook Islands'},
                { value: 71, label: 'Costa Rica'},
                { value: 72, label: 'Cote D\'ivoire'},
                { value: 73, label: 'Croatia'},
                { value: 74, label: 'Cuba'},
                { value: 75, label: 'Curaçao'},
                { value: 76, label: 'Cyprus'},
                { value: 77, label: 'Czech Republic'},
                { value: 78, label: 'Denmark'},
                { value: 79, label: 'Djibouti'},
                { value: 80, label: 'Dominica'},
                { value: 81, label: 'Dominican Republic'},
                { value: 82, label: 'Ecuador'},
                { value: 83, label: 'Egypt'},
                { value: 84, label: 'El Salvador'},
                { value: 85, label: 'Equatorial Guinea'},
                { value: 86, label: 'Eritrea'},
                { value: 87, label: 'Estonia'},
                { value: 88, label: 'Eswatini'},
                { value: 89, label: 'Ethiopia'},
                { value: 90, label: 'Falkland Islands (Malvinas)'},
                { value: 91, label: 'Faroe Islands'},
                { value: 92, label: 'Fiji'},
                { value: 93, label: 'Finland'},
                { value: 94, label: 'France'},
                { value: 95, label: 'French Guiana'},
                { value: 96, label: 'French Polynesia'},
                { value: 97, label: 'French Southern Territories'},
                { value: 98, label: 'Gabon'},
                { value: 99, label: 'Gambia'},
                { value: 100 , label: 'Georgia'},
                { value: 101 , label: 'Germany'},
                { value: 102 , label: 'Ghana'},
                { value: 103 , label: 'Gibraltar'},
                { value: 104 , label: 'Greece'},
                { value: 105 , label: 'Greenland'},
                { value: 106 , label: 'Grenada'},
                { value: 107 , label: 'Guadeloupe'},
                { value: 108 , label: 'Guam'},
                { value: 109 , label: 'Guatemala'},
                { value: 110 , label: 'Guernsey'},
                { value: 111 , label: 'Guinea'},
                { value: 112 , label: 'Guinea-bissau'},
                { value: 113 , label: 'Guyana'},
                { value: 114 , label: 'Haiti'},
                { value: 115 , label: 'Heard Island and Mcdonald Islands'},
                { value: 116 , label: 'Holy See (Vatican City State)'},
                { value: 117 , label: 'Honduras'},
                { value: 118 , label: 'Hong Kong'},
                { value: 119 , label: 'Hungary'},
                { value: 120 , label: 'Iceland'},
                { value: 121 , label: 'India'},
                { value: 122 , label: 'Indonesia'},
                { value: 123 , label: 'Iran, Islamic Republic of'},
                { value: 124 , label: 'Iraq'},
                { value: 125 , label: 'Ireland'},
                { value: 126 , label: 'Isle of Man'},
                { value: 127 , label: 'Israel'},
                { value: 128 , label: 'Italy'},
                { value: 129 , label: 'Jamaica'},
                { value: 130 , label: 'Japan'},
                { value: 131 , label: 'Jersey'},
                { value: 132 , label: 'Jordan'},
                { value: 133 , label: 'Kazakhstan'},
                { value: 134 , label: 'Kenya'},
                { value: 135 , label: 'Kiribati'},
                { value: 136 , label: 'Korea, Democratic People\'s Republic of'},
                { value: 137 , label: 'Korea, Republic of'},
                { value: 138 , label: 'Kuwait'},
                { value: 139 , label: 'Kyrgyzstan'},
                { value: 140 , label: 'Lao People\'s Democratic Republic'},
                { value: 141 , label: 'Latvia'},
                { value: 142 , label: 'Lebanon'},
                { value: 143 , label: 'Lesotho'},
                { value: 144 , label: 'Liberia'},
                { value: 145 , label: 'Libyan Arab Jamahiriya'},
                { value: 146 , label: 'Liechtenstein'},
                { value: 147 , label: 'Lithuania'},
                { value: 148 , label: 'Luxembourg'},
                { value: 149 , label: 'Macao'},
                { value: 267 , label: 'Macedonia, The Former Yugoslav Republic of'},
                { value: 150 , label: 'Madagascar'},
                { value: 151 , label: 'Malawi'},
                { value: 152 , label: 'Malaysia'},
                { value: 153 , label: 'Maldives'},
                { value: 154 , label: 'Mali'},
                { value: 155 , label: 'Malta'},
                { value: 156 , label: 'Marshall Islands'},
                { value: 157 , label: 'Martinique'},
                { value: 158 , label: 'Mauritania'},
                { value: 159 , label: 'Mauritius'},
                { value: 160 , label: 'Mayotte'},
                { value: 161 , label: 'Mexico'},
                { value: 162 , label: 'Micronesia, Federated States of'},
                { value: 163 , label: 'Moldova, Republic of'},
                { value: 164 , label: 'Monaco'},
                { value: 165 , label: 'Mongolia'},
                { value: 166 , label: 'Montenegro'},
                { value: 167 , label: 'Montserrat'},
                { value: 168 , label: 'Morocco'},
                { value: 169 , label: 'Mozambique'},
                { value: 170 , label: 'Myanmar'},
                { value: 171 , label: 'Namibia'},
                { value: 172 , label: 'Nauru'},
                { value: 173 , label: 'Nepal'},
                { value: 174 , label: 'Netherlands'},
                { value: 268 , label: 'Netherlands Antilles'},
                { value: 175 , label: 'New Caledonia'},
                { value: 176 , label: 'New Zealand'},
                { value: 177 , label: 'Nicaragua'},
                { value: 178 , label: 'Niger'},
                { value: 179 , label: 'Nigeria'},
                { value: 180 , label: 'Niue'},
                { value: 181 , label: 'Norfolk Island'},
                { value: 182 , label: 'North Macedonia'},
                { value: 183 , label: 'Northern Mariana Islands'},
                { value: 184 , label: 'Norway'},
                { value: 185 , label: 'Oman'},
                { value: 186 , label: 'Pakistan'},
                { value: 187 , label: 'Palau'},
                { value: 188 , label: 'Palestine jehuda & sumeria'},
                { value: 269 , label: 'Palestine gaza strip'},
                { value: 189 , label: 'Panama'},
                { value: 190 , label: 'Papua New Guinea'},
                { value: 191 , label: 'Paraguay'},
                { value: 192 , label: 'Peru'},
                { value: 193 , label: 'Philippines'},
                { value: 194 , label: 'Pitcairn'},
                { value: 195 , label: 'Poland'},
                { value: 196 , label: 'Portugal'},
                { value: 197 , label: 'Puerto Rico'},
                { value: 198 , label: 'Qatar'},
                { value: 199 , label: 'Reunion'},
                { value: 200 , label: 'Romania'},
                { value: 201 , label: 'Russian Federation'},
                { value: 202 , label: 'Rwandan'},
                { value: 203 , label: 'Saint Barthélemyn'},
                { value: 204 , label: 'Saint Helenan'},
                { value: 205 , label: 'Saint Kitts and Nevis'},
                { value: 206 , label: 'Saint Lucia'},
                { value: 207 , label: 'Saint Martin (French part)'},
                { value: 208 , label: 'Saint Pierre and Miquelon'},
                { value: 209 , label: 'Saint Vincent and The Grenadines'},
                { value: 210 , label: 'Samoa'},
                { value: 211 , label: 'San Marino'},
                { value: 212 , label: 'Sao Tome and Principe'},
                { value: 213 , label: 'Saudi Arabia'},
                { value: 214 , label: 'Senegal'},
                { value: 215 , label: 'Serbia'},
                { value: 216 , label: 'Seychelles'},
                { value: 217 , label: 'Sierra Leone'},
                { value: 218 , label: 'Singapore'},
                { value: 219 , label: 'Sint Maarten (Dutch part)'},
                { value: 220 , label: 'Slovakia'},
                { value: 221 , label: 'Slovenia'},
                { value: 222 , label: 'Solomon Islands'},
                { value: 223 , label: 'Somalia'},
                { value: 224 , label: 'South Africa'},
                { value: 225 , label: 'South Georgia and The South Sandwich Islands'},
                { value: 226 , label: 'South Sudan'},
                { value: 227 , label: 'Spain'},
                { value: 228 , label: 'Sri Lanka'},
                { value: 229 , label: 'Sudan'},
                { value: 230 , label: 'Suriname'},
                { value: 231 , label: 'Svalbard and Jan Mayen'},
                { value: 270 , label: 'Swaziland'},
                { value: 232 , label: 'Sweden'},
                { value: 233 , label: 'Switzerland'},
                { value: 234 , label: 'Syrian Arab Republic'},
                { value: 235 , label: 'Taiwan'},
                { value: 236 , label: 'Tajikistan'},
                { value: 237 , label: 'Tanzania, United Republic of'},
                { value: 238 , label: 'Thailand'},
                { value: 239 , label: 'Timor-leste'},
                { value: 240 , label: 'Togo'},
                { value: 241 , label: 'Tokelau'},
                { value: 242 , label: 'Tonga'},
                { value: 243 , label: 'Trinidad and Tobago'},
                { value: 244 , label: 'Tunisia'},
                { value: 245 , label: 'Turkey'},
                { value: 246 , label: 'Turkmenistan'},
                { value: 247 , label: 'Turks and Caicos Islands'},
                { value: 248 , label: 'Tuvalu'},
                { value: 249 , label: 'Uganda'},
                { value: 250 , label: 'Ukraine'},
                { value: 251 , label: 'United Arab Emirates'},
                { value: 252 , label: 'United Kingdom'},
                { value: 253 , label: 'United States'},
                { value: 254 , label: 'United States Minor Outlying Islands'},
                { value: 255 , label: 'Uruguay'},
                { value: 256 , label: 'Uzbekistan'},
                { value: 257 , label: 'Vanuatu'},
                { value: 258 , label: 'Venezuela'},
                { value: 259 , label: 'Viet Nam'},
                { value: 260 , label: 'Virgin Islands, British'},
                { value: 261 , label: 'Virgin Islands, U.S.'},
                { value: 262 , label: 'Wallis and Futuna'},
                { value: 263 , label: 'Western Sahara'},
                { value: 264 , label: 'Yemen'},
                { value: 265 , label: 'Zambia'},
                { value: 266 , label: 'Zimbabwe'},
              ]
const namefil = `country`
const placeholder = `Take your pick...`
const required = true

let selected
	
import { createForm } from "svelte-forms-lib";

    const { form, handleChange, handleSubmit } = createForm({
      initialValues: {
        name: "",
        email: "",
        country: []
      },
      onSubmit: values => {
        fetch('http://localhost:5000/chezins', {
  method: 'POST',
  headers: {
    'Content-Type': 'application/json',
  },
  body: JSON.stringify({
    name: $form.name,
    email: $form.email,
    countries: [$form.country],
  }),
}) 
  .then(response => response.json())
  .then(data => console.log(data));
        alert(JSON.stringify(values));
      }
    });
  </script>

  <form dir="rtl"
  on:submit={handleSubmit}>

  
    <label for="name">
		שם
	</label>
    <input 
      id="name"
      name="name"
      required
      on:change={handleChange}
      bind:value={$form.name}
    />

    <label for="email">מייל</label>
    <input
      id="email"
      name="email"
      required
      on:change={handleChange}
      bind:value={$form.email}
    />

  <MultiSelect bind:selected {namefil} {placeholder} options={country.label} {required} />
           
    <button type="submit">יציאה לחופשי</button>   

</form>

**Comment by Avi-ADAM** [comment]
`
<script>

import MultiSelect from 'svelte-multiselect'

const country =  [
                { value: 17, label: 'Åland Islands'},
                { value: 18, label: 'Afghanistan'},
                { value: 19, label: 'Albania'},
                { value: 20, label: 'Algeria'},
                { value: 21, label: 'American Samoa'},
                { value: 22, label: 'Andorra'},
                { value: 23, label: 'Angola'},
                { value: 24, label: 'Anguilla'},
                { value: 25, label: 'Antarctica'},
                { value: 26, label: 'Antigua and Barbuda'},
                { value: 27, label: 'Argentina'},
                { value: 28, label: 'Armenia'},
                { value: 29, label: 'Aruba'},
                { value: 30, label: 'Australia'},
                { value: 31, label: 'Austria'},
                { value: 32, label: 'Azerbaijan'},
                { value: 33, label: 'Bahamas'},
                { value: 34, label: 'Bahrain'},
                { value: 35, label: 'Bangladesh'},
                { value: 36, label: 'Barbados'},
                { value: 37, label: 'Belarus'},
                { value: 38, label: 'Belgium'},
                { value: 40, label: 'Belize'},
                { value: 41, label: 'Benin'},
                { value: 42, label: 'Bermuda'},
                { value: 43, label: 'Bhutan'},
                { value: 44, label: 'Bolivia'},
                { value: 45, label: 'Bonaire, Sint Eustatius and Saba'},
                { value: 46, label: 'Bosnia and Herzegovina'},
                { value: 47, label: 'Botswana'},
                { value: 48, label: 'Bouvet Island'},
                { value: 49, label: 'Brazil'},
                { value: 50, label: 'British Indian Ocean Territory'},
                { value: 51, label: 'Brunei Darussalam'},
                { value: 52, label: 'Bulgaria'},
                { value: 53, label: 'Burkina Faso</'}, 
                { value: 54, label: 'Burundi</'}, 
                { value: 55, label: 'Cambodia</'}, 
                { value: 56, label: 'Cameroon</'}, 
                { value: 57, label: 'Canada</'}, 
                { value: 58, label: 'Cape Verde</'}, 
                { value: 59, label: 'Cayman Islands'}, 
                { value: 60, label: 'Central African Republic'},
                { value: 61, label: 'Chad'},
                { value: 62, label: 'Chile'},
                { value: 63, label: 'China'},
                { value: 64, label: 'Christmas Island'},
                { value: 65, label: 'Cocos (Keeling) Islands'},
                { value: 66, label: 'Colombia'},
                { value: 67, label: 'Comoros'},
                { value: 68, label: 'Congo'},
                { value: 69, label: 'Congo, The Democratic Republic of The'},
                { value: 70, label: 'Cook Islands'},
                { value: 71, label: 'Costa Rica'},
                { value: 72, label: 'Cote D\'ivoire'},
                { value: 73, label: 'Croatia'},
                { value: 74, label: 'Cuba'},
                { value: 75, label: 'Curaçao'},
                { value: 76, label: 'Cyprus'},
                { value: 77, label: 'Czech Republic'},
                { value: 78, label: 'Denmark'},
                { value: 79, label: 'Djibouti'},
                { value: 80, label: 'Dominica'},
                { value: 81, label: 'Dominican Republic'},
                { value: 82, label: 'Ecuador'},
                { value: 83, label: 'Egypt'},
                { value: 84, label: 'El Salvador'},
                { value: 85, label: 'Equatorial Guinea'},
                { value: 86, label: 'Eritrea'},
                { value: 87, label: 'Estonia'},
                { value: 88, label: 'Eswatini'},
                { value: 89, label: 'Ethiopia'},
                { value: 90, label: 'Falkland Islands (Malvinas)'},
                { value: 91, label: 'Faroe Islands'},
                { value: 92, label: 'Fiji'},
                { value: 93, label: 'Finland'},
                { value: 94, label: 'France'},
                { value: 95, label: 'French Guiana'},
                { value: 96, label: 'French Polynesia'},
                { value: 97, label: 'French Southern Territories'},
                { value: 98, label: 'Gabon'},
                { value: 99, label: 'Gambia'},
                { value: 100 , label: 'Georgia'},
                { value: 101 , label: 'Germany'},
                { value: 102 , label: 'Ghana'},
                { value: 103 , label: 'Gibraltar'},
                { value: 104 , label: 'Greece'},
                { value: 105 , label: 'Greenland'},
                { value: 106 , label: 'Grenada'},
                { value: 107 , label: 'Guadeloupe'},
                { value: 108 , label: 'Guam'},
                { value: 109 , label: 'Guatemala'},
                { value: 110 , label: 'Guernsey'},
                { value: 111 , label: 'Guinea'},
                { value: 112 , label: 'Guinea-bissau'},
                { value: 113 , label: 'Guyana'},
                { value: 114 , label: 'Haiti'},
                { value: 115 , label: 'Heard Island and Mcdonald Islands'},
                { value: 116 , label: 'Holy See (Vatican City State)'},
                { value: 117 , label: 'Honduras'},
                { value: 118 , label: 'Hong Kong'},
                { value: 119 , label: 'Hungary'},
                { value: 120 , label: 'Iceland'},
                { value: 121 , label: 'India'},
                { value: 122 , label: 'Indonesia'},
                { value: 123 , label: 'Iran, Islamic Republic of'},
                { value: 124 , label: 'Iraq'},
                { value: 125 , label: 'Ireland'},
                { value: 126 , label: 'Isle of Man'},
                { value: 127 , label: 'Israel'},
                { value: 128 , label: 'Italy'},
                { value: 129 , label: 'Jamaica'},
                { value: 130 , label: 'Japan'},
                { value: 131 , label: 'Jersey'},
                { value: 132 , label: 'Jordan'},
                { value: 133 , label: 'Kazakhstan'},
                { value: 134 , label: 'Kenya'},
                { value: 135 , label: 'Kiribati'},
                { value: 136 , label: 'Korea, Democratic People\'s Republic of'},
                { value: 137 , label: 'Korea, Republic of'},
                { value: 138 , label: 'Kuwait'},
                { value: 139 , label: 'Kyrgyzstan'},
                { value: 140 , label: 'Lao People\'s Democratic Republic'},
                { value: 141 , label: 'Latvia'},
                { value: 142 , label: 'Lebanon'},
                { value: 143 , label: 'Lesotho'},
                { value: 144 , label: 'Liberia'},
                { value: 145 , label: 'Libyan Arab Jamahiriya'},
                { value: 146 , label: 'Liechtenstein'},
                { value: 147 , label: 'Lithuania'},
                { value: 148 , label: 'Luxembourg'},
                { value: 149 , label: 'Macao'},
                { value: 267 , label: 'Macedonia, The Former Yugoslav Republic of'},
                { value: 150 , label: 'Madagascar'},
                { value: 151 , label: 'Malawi'},
                { value: 152 , label: 'Malaysia'},
                { value: 153 , label: 'Maldives'},
                { value: 154 , label: 'Mali'},
                { value: 155 , label: 'Malta'},
                { value: 156 , label: 'Marshall Islands'},
                { value: 157 , label: 'Martinique'},
                { value: 158 , label: 'Mauritania'},
                { value: 159 , label: 'Mauritius'},
                { value: 160 , label: 'Mayotte'},
                { value: 161 , label: 'Mexico'},
                { value: 162 , label: 'Micronesia, Federated States of'},
                { value: 163 , label: 'Moldova, Republic of'},
                { value: 164 , label: 'Monaco'},
                { value: 165 , label: 'Mongolia'},
                { value: 166 , label: 'Montenegro'},
                { value: 167 , label: 'Montserrat'},
                { value: 168 , label: 'Morocco'},
                { value: 169 , label: 'Mozambique'},
                { value: 170 , label: 'Myanmar'},
                { value: 171 , label: 'Namibia'},
                { value: 172 , label: 'Nauru'},
                { value: 173 , label: 'Nepal'},
                { value: 174 , label: 'Netherlands'},
                { value: 268 , label: 'Netherlands Antilles'},
                { value: 175 , label: 'New Caledonia'},
                { value: 176 , label: 'New Zealand'},
                { value: 177 , label: 'Nicaragua'},
                { value: 178 , label: 'Niger'},
                { value: 179 , label: 'Nigeria'},
                { value: 180 , label: 'Niue'},
                { value: 181 , label: 'Norfolk Island'},
                { value: 182 , label: 'North Macedonia'},
                { value: 183 , label: 'Northern Mariana Islands'},
                { value: 184 , label: 'Norway'},
                { value: 185 , label: 'Oman'},
                { value: 186 , label: 'Pakistan'},
                { value: 187 , label: 'Palau'},
                { value: 188 , label: 'Palestine jehuda & sumeria'},
                { value: 269 , label: 'Palestine gaza strip'},
                { value: 189 , label: 'Panama'},
                { value: 190 , label: 'Papua New Guinea'},
                { value: 191 , label: 'Paraguay'},
                { value: 192 , label: 'Peru'},
                { value: 193 , label: 'Philippines'},
                { value: 194 , label: 'Pitcairn'},
                { value: 195 , label: 'Poland'},
                { value: 196 , label: 'Portugal'},
                { value: 197 , label: 'Puerto Rico'},
                { value: 198 , label: 'Qatar'},
                { value: 199 , label: 'Reunion'},
                { value: 200 , label: 'Romania'},
                { value: 201 , label: 'Russian Federation'},
                { value: 202 , label: 'Rwandan'},
                { value: 203 , label: 'Saint Barthélemyn'},
                { value: 204 , label: 'Saint Helenan'},
                { value: 205 , label: 'Saint Kitts and Nevis'},
                { value: 206 , label: 'Saint Lucia'},
                { value: 207 , label: 'Saint Martin (French part)'},
                { value: 208 , label: 'Saint Pierre and Miquelon'},
                { value: 209 , label: 'Saint Vincent and The Grenadines'},
                { value: 210 , label: 'Samoa'},
                { value: 211 , label: 'San Marino'},
                { value: 212 , label: 'Sao Tome and Principe'},
                { value: 213 , label: 'Saudi Arabia'},
                { value: 214 , label: 'Senegal'},
                { value: 215 , label: 'Serbia'},
                { value: 216 , label: 'Seychelles'},
                { value: 217 , label: 'Sierra Leone'},
                { value: 218 , label: 'Singapore'},
                { value: 219 , label: 'Sint Maarten (Dutch part)'},
                { value: 220 , label: 'Slovakia'},
                { value: 221 , label: 'Slovenia'},
                { value: 222 , label: 'Solomon Islands'},
                { value: 223 , label: 'Somalia'},
                { value: 224 , label: 'South Africa'},
                { value: 225 , label: 'South Georgia and The South Sandwich Islands'},
                { value: 226 , label: 'South Sudan'},
                { value: 227 , label: 'Spain'},
                { value: 228 , label: 'Sri Lanka'},
                { value: 229 , label: 'Sudan'},
                { value: 230 , label: 'Suriname'},
                { value: 231 , label: 'Svalbard and Jan Mayen'},
                { value: 270 , label: 'Swaziland'},
                { value: 232 , label: 'Sweden'},
                { value: 233 , label: 'Switzerland'},
                { value: 234 , label: 'Syrian Arab Republic'},
                { value: 235 , label: 'Taiwan'},
                { value: 236 , label: 'Tajikistan'},
                { value: 237 , label: 'Tanzania, United Republic of'},
                { value: 238 , label: 'Thailand'},
                { value: 239 , label: 'Timor-leste'},
                { value: 240 , label: 'Togo'},
                { value: 241 , label: 'Tokelau'},
                { value: 242 , label: 'Tonga'},
                { value: 243 , label: 'Trinidad and Tobago'},
                { value: 244 , label: 'Tunisia'},
                { value: 245 , label: 'Turkey'},
                { value: 246 , label: 'Turkmenistan'},
                { value: 247 , label: 'Turks and Caicos Islands'},
                { value: 248 , label: 'Tuvalu'},
                { value: 249 , label: 'Uganda'},
                { value: 250 , label: 'Ukraine'},
                { value: 251 , label: 'United Arab Emirates'},
                { value: 252 , label: 'United Kingdom'},
                { value: 253 , label: 'United States'},
                { value: 254 , label: 'United States Minor Outlying Islands'},
                { value: 255 , label: 'Uruguay'},
                { value: 256 , label: 'Uzbekistan'},
                { value: 257 , label: 'Vanuatu'},
                { value: 258 , label: 'Venezuela'},
                { value: 259 , label: 'Viet Nam'},
                { value: 260 , label: 'Virgin Islands, British'},
                { value: 261 , label: 'Virgin Islands, U.S.'},
                { value: 262 , label: 'Wallis and Futuna'},
                { value: 263 , label: 'Western Sahara'},
                { value: 264 , label: 'Yemen'},
                { value: 265 , label: 'Zambia'},
                { value: 266 , label: 'Zimbabwe'},
              ]
const namefil = `country`
const placeholder = `Take your pick...`
const required = true

let selected
	
import { createForm } from "svelte-forms-lib";

    const { form, handleChange, handleSubmit } = createForm({
      initialValues: {
        name: "",
        email: "",
        country: []
      },
      onSubmit: values => {
        fetch('http://localhost:5000/chezins', {
  method: 'POST',
  headers: {
    'Content-Type': 'application/json',
  },
  body: JSON.stringify({
    name: $form.name,
    email: $form.email,
    countries: [$form.country],
  }),
}) 
  .then(response => response.json())
  .then(data => console.log(data));
        alert(JSON.stringify(values));
      }
    });
  </script>

  <form dir="rtl"
  on:submit={handleSubmit}>

  
    <label for="name">
		שם
	</label>
    <input 
      id="name"
      name="name"
      required
      on:change={handleChange}
      bind:value={$form.name}
    />

    <label for="email">מייל</label>
    <input
      id="email"
      name="email"
      required
      on:change={handleChange}
      bind:value={$form.email}
    />

  <MultiSelect bind:selected {namefil} {placeholder} options={country.label} {required} />
           
    <button type="submit">יציאה לחופשי</button>   

</form>`

**Comment by janosh** [comment]
So that's what I was asking above. `MultiSelect` doesn't currently support passing options as an array of objects. In its current implementation, you'd have to get rid of the country values and pass in only the country names:

```svelte
<MultiSelect bind:selected {namefil} {placeholder} options={country.map(c => c.label)} {required} />
```
