### ISSUE TITLE
FR: Enable asynchronous adding of options

### ISSUE THREAD

**Issue by ranielzed** [janosh/svelte-multiselect#100]
Thanks for your efforts on this component! It works and caters to most of my needs. There's just a few instances that I need users to add options. In this case, post the new item to an endpoint and add that option to the DB. 

Adding this feature would enable me to listen in on the server call and show the loading spinner and show error messages when it fails.

Thanks for considering this!

**Comment by janosh** [comment]
Glad you like it. Could you provide a specific example? From what you describe, it sounds like your use case is already covered by setting `allowUserOptions="append"` and the `loading` prop. See [/allow-user-options](https://svelte-multiselect.netlify.app/allow-user-options) and the [loading indicator on text input](https://svelte-multiselect.netlify.app) example.

**Comment by janosh** [comment]
You can pass a callback to the `on:add` event in which you POST new options to a database:

```svelte
<MultiSelect
  options={colors}
  placeholder="Pick some colors..."
  allowUserOptions="append"
  on:add={(event) => {
    // if you want to persist new user entered custom options to a database, perform
    // a fetch request with type POST here using the event.detail.option payload
    console.log(event.detail.option) // will be a string like `"Unusual color"` or an object `{ label: "Unusual color", value: "Unusual color" }` depending on your other options
  }}
>
```

**Comment by janosh** [comment]
See [the `colors` example REPL](https://svelte.dev/repl/a5a14b8f15d64cb083b567292480db05?version=3.49.0) to try this in action.

**Comment by janosh** [comment]
Cool. Please reopen this issue if you encounter any problems.
