### ISSUE TITLE
Error of Unknown file extension ".svelte" in SvelteKit

### ISSUE THREAD

**Issue by lysdexic-audio** [janosh/svelte-multiselect#104]
I got this error today after installing via npm `npm install -D svelte-multiselect`

> 500 Error of Unknown file extension ".svelte" in SvelteKit

I used [this workaround](https://github.com/hperrin/svelte-material-ui/issues/375#issuecomment-994158467) to fix it in the short term - looks like `package.json` might need to be adjusted for this module?

**Comment by janosh** [comment]
Could you provide a reproduction? `svelte-multiselect@6.0.0` is working in all the SvelteKit projects where I use it so can't reproduce.

The workaround you linked mentions that the reason for the error might a missing `main` field in `svelte-material-ui`'s `package.json` which this package has. Not sure what to change.

https://github.com/janosh/svelte-multiselect/blob/224144dce012d1eef515abafa542c6a6b7e063e8/package.json#L9-L11

**Comment by janosh** [comment]
Closing this as stale. Happy to re-open on further details/a repro.
