### ISSUE TITLE
Tags added by users are strings instead of `ObjectOption` when there's no options

### ISSUE THREAD

**Issue by abhijit-hota** [janosh/svelte-multiselect#106]
I have to do API calls based on user-added tags or not hence I filter them via the following function:

```js
const isNewTag = (tag: ObjectOption) => tag.label == tag.value && typeof tag.value === "string";
```

This logic works when the MultiSelect component already has some data because the newly added options by users gets converted to an object. But if the component does not receive any options, and the only options in the list are user-added, then it's just a string.

I can check for this and change my logic but I was wondering if there's a native way to handle this.

My component:

```html
<script lang="ts">
  const isNewTag = (tag: ObjectOption) => tag.label == tag.value && typeof tag.value === "string";
  let selectedTags: ObjectOption[] = [];
  $: newTags = selectedTags.filter(isNewTag);
</script>

<MultiSelect
  inputClass="input-like"
  outerDivClass="color-fix"
  allowUserOptions="append"
  addOptionMsg="+ Create new tag"
  options={$tags.map(({ id, name }) => ({ label: name, value: id }))}
  bind:selected={selectedTags}
/>
```

**Comment by janosh** [comment]
> I can check for this and change my logic but I was wondering if there's a native way to handle this.

Not yet. But I see how that could be useful. We could add a new prop 

```js
userInputAs: 'object' | 'string' | 'number' = options.length > 0 ? typeof options[0] : 'string'
```

which defaults to the type of options already passed and `'string'` if none were passed.

In your case, you would pass

```html
<MultiSelect
  userInputAs='object'
/>
```

to ensure all newly created options from user input become objects.

**Comment by abhijit-hota** [comment]
This does seem like a solution. However, I'll repeat what I said in https://github.com/janosh/svelte-multiselect/issues/107#issuecomment-1248982138. I don't think a prop is needed for a specific use-case like this.

But obviously, the decision is yours!

**Comment by janosh** [comment]
I agree it is a niche use case but there's currently no way of enforcing options become objects when starting from an empty Multiselect so a new prop definitely has some merit. Will decide later.

**Comment by janosh** [comment]
Decided to close this issue without adding the new prop for now as when starting with an empty multiselect, it's probably used as a tag input where the current behavior of returning options as strings is probably desired in most cases. We can revisit the decision if the issue ever comes up again.
