### ISSUE TITLE
Keyboard control not working on 6.0.x

### ISSUE THREAD

**Issue by monks1975** [janosh/svelte-multiselect#110]
Has anything change re: keyboard control (arrow keys on input focus to move to the options dropdown), as it stopped working for me some versions ago, maybe when going to v6. It doesn't seem to work for me on Chrome 105 on your homepage examples either, so not sure if this is now something the dev has to apply themselves. Have not seen any recent issues about it.

**Comment by janosh** [comment]
Good catch! I broke this myself in https://github.com/janosh/svelte-multiselect/commit/50bb45e which was released as the currently latest version [v6.0.2](https://github.com/janosh/svelte-multiselect/releases/tag/v6.0.2) 3 days ago. Luckily it's a simple fix. I'll also add a test to prevent future regressions.
