### ISSUE TITLE
Cannot select the top option with enter

### ISSUE THREAD

**Issue by ciscoheat** [janosh/svelte-multiselect#112]
I'm trying out the Favorite programming languages demo, but I cannot select the top option in the menu by pressing enter? By using the arrows keys and moving down, it works. Using Chrome 105 on Win 10.

**Comment by janosh** [comment]
Good catch and thanks for reporting! Should be east to fix.

**Comment by ciscoheat** [comment]
Thanks for the quick fix. It looks great. :)

**Comment by janosh** [comment]
Released in [v6.1.0](https://github.com/janosh/svelte-multiselect/releases/tag/v6.1.0).
