### ISSUE TITLE
`Escape` keypress closes Bootstrap Modal when multi-select is inside the Modal

### ISSUE THREAD

**Issue by Snailedlt** [janosh/svelte-multiselect#114]
## Introduction
When the multiselect component is inside of a modal it's not possible to close it with the `escape` key. Instead it closes the entire Modal.
This doesn't happen with a normal `<select>` HTML element.

Here's a little repl and video to show you more clearly: https://svelte.dev/repl/6a6073ad3f6c4ce28545b64290a4c433?version=3.50.1

https://user-images.githubusercontent.com/43886029/192564879-e45a280e-b39e-4599-b50f-5e9fccbe3746.mp4

### Steps to reproduce
1. tab to modal
2. hit enter to open modal
3. tab to the MultiSelect field
4. hit escape to close

### Expected result
MultiSelect field closes, and Modal stays open.

### Actual result
Modal closes

**Comment by Snailedlt** [comment]
Managed to work around the issue by surrounding the MultiSelect with a div containing the `on:keydown|stopPropagation` attribute
```svelte
<div on:keydown|stopPropagation>
    <MultiSelect bind:selected options={ui_libs} />
</div>
```

**Comment by janosh** [comment]
Thanks for the detailed report and the REPL link! 👍

Adding `stopPropagation` to the `keydown` handler sounds like a sensible change. Fix incoming.

**Comment by janosh** [comment]
@Snailedlt The fix is not yet released. I'll cut a new release soon once #123 is merged. Once that's out it's as simple as telling your package manager (`npm`, `yarn`, `pnpm`) to update `svelte-multiselect` followed by consulting the readme to see if any of the [recent breaking changes](https://github.com/janosh/svelte-multiselect#recent-breaking-changes) concern you.

**Comment by Snailedlt** [comment]
Great, thanks a lot!

**Comment by janosh** [comment]
This is out now in [v7.0.0](https://github.com/janosh/svelte-multiselect/releases/tag/v7.0.0).
