### ISSUE TITLE
No input masking for elements

### ISSUE THREAD

**Issue by jameswright1562** [janosh/svelte-multiselect#119]
I cannot get elements to mask (e.g. colon between minute and hour) to occur. Also there is no method to call a method in the script upon a user inputting something.

**Comment by janosh** [comment]
> I cannot get elements to mask (e.g. colon between minute and hour) to occur.

Not sure what you mean by that. Could you explain further in a new issue? One thing per issue makes it easier to associate PRs with issues.

> Also there is no method to call a method in the script upon a user inputting something.

Good point. I'll add this.
