### ISSUE TITLE
TypeError: Cannot read properties of null (reading 'get_label') at MultiSelect.svelte:75

### ISSUE THREAD

**Issue by janosh** [janosh/svelte-multiselect#121]
[In rare cases](https://github.com/sbsev/svelte-site/actions/runs/3169667849/jobs/5161736794#step:5:24) the line `$: selectedLabels = selected.map(get_label)`

https://github.com/janosh/svelte-multiselect/blob/8ab0d21a9793402fa8332bc9ced1fc3bcb340b24/src/lib/MultiSelect.svelte#L84-L85

raises

```
TypeError: Cannot read properties of null (reading 'get_label')
    at MultiSelect.svelte:75:33
```

Not sure exactly what is becoming `null` and what's trying to access `null.get_label` but

```svelte
$: selectedLabels = selected?.map(get_label) ?? []
```

seems to fix it.

**Comment by jesi-rgb** [comment]
Hello, Janosh! First of all, thanks so much for this awesome component.

Getting straight to the point, I am running a lot into this specific error in my project using the library.

```diff
<script>
  const particleOptions = [`todavía`, `tampoco`, `ni aun`];
  let selected = [];
</script>

<div class="flex flex-col items-start space-y-5">
  <div class="flex flex-col xl:flex-row space-x-8 w-full mx-auto">
+    <MultiSelect bind:selected options={particleOptions} />
    <table class="mb-4 xl:w-3/4">
```

I believe I am using the component properly, and it has worked so far with this exact code until... it didn't for some reason. I am trying to search for the changes I made but... none seem relevant.

If you need to take a deeper look, everything is [under this file in my repository](https://github.com/jesi-rgb/particulas-db/blob/main/src/lib/SvTable.svelte).

Thanks again beforehand for all your effort. If you were able to somehow help me out on this one, it'd be awesome.

Hope you have a super nice day!

**Comment by janosh** [comment]
@jesi-rgb Thanks for reporting this! I'm also still seeing this same error but just in 1 one the dozen repos where I use `svelte-multiselect`.

https://github.com/sbsev/site/actions/runs/3200455674/jobs/5227373091#step:5:42

Have yet to figure out what exactly is going wrong and how to fix. https://github.com/janosh/svelte-multiselect/pull/122 apparently didn't solve the problem like I originally thought. Maybe comparing your repo with https://github.com/sbsev/site can reveal what sets them apart, i.e. why the error is only happening there.

**Comment by janosh** [comment]
Looks like my hunch about a circular module import was correct https://github.com/janosh/svelte-multiselect/pull/131/commits/75232710d2796b242a8833975f96fabea403e8b7.

[v7.0.2](https://github.com/janosh/svelte-multiselect/releases/tag/v7.0.2) fixes it for real, at least on the repo I mentioned above: https://github.com/sbsev/site/actions/runs/3211769303/jobs/5250168078

Would be interested to hear if it solves your problem too.

**Comment by jesi-rgb** [comment]
You are the absolute best. Cannot check right now but will tomorrow morning. Thanks anyways for your effort!

**Comment by jesi-rgb** [comment]
Janosh, this works perfectly now. Thanks SO much for your super quick attention and fix, you're literally the best.

Have a great Sunday!
