### ISSUE TITLE
Add ability to prevent users from select/creating duplicate options

### ISSUE THREAD

**Issue by oskar-gmerek** [janosh/svelte-multiselect#125]
I think it would be great to be able to prevent duplicates from being selected/added.

For example:
If I chose the "Pineapple" option and put "Pineapple" in the input, the message `duplicateOptionMsg` should be displayed instead of `addOptionMsg` (eg: 'Already selected').

**Comment by janosh** [comment]
Agreed. The way this component handles duplicate options could be clearer/more explicit in general (i.e. also in cases when users don't have the ability to create new custom options).
