### ISSUE TITLE
The examples on top of the website should have a heading

### ISSUE THREAD

**Issue by Snailedlt** [janosh/svelte-multiselect#146]
The exampels at the top of the website currently have no heading. This means that it's not easy to navigate to it if we were to scroll to the bottom of the website. A new heading should be added:

Before: 
![image](https://user-images.githubusercontent.com/43886029/199449820-5ad2e320-4dea-4729-af14-a58117b3a1fb.png)

After: 
![image](https://user-images.githubusercontent.com/43886029/199449854-45c7895d-98da-4bd0-b9d5-6d81d4294a45.png)

Couldn't find the code for the website, but here's the code that should be added:
```html
<h2 id="examples" class="">Examples<a aria-hidden="true" tabindex="-1" href="#examples"><svg width="16" height="16" viewBox="0 0 16 16"><use xlink:href="#octicon-link"></use></svg></a></h2>
```

**Comment by janosh** [comment]
Thanks for all the doc improvement suggestions btw. Much appreciated! 👍

**Comment by Snailedlt** [comment]
@janosh Happy to help! Especially when you're so insanely quick at fixing the issues!

I wanted to make a PR for some of the improvements, but couldn't find the website code, is it open sourced... if so, got a link?

**Comment by janosh** [comment]
Yes, all code relevant to this project lives in this repo. Except for the REPLs.

The stuff you see on https://svelte-multiselect.netlify.app is mostly in 
https://github.com/janosh/svelte-multiselect/tree/main/src/components
and
https://github.com/janosh/svelte-multiselect/tree/main/src/routes.

The landing page just imports the readme and inserts two slot components for the examples and nav bar below it.

https://github.com/janosh/svelte-multiselect/blob/ba509a1e2dbf39d070ce3dbe59df3dfd32e171f4/src/routes/%2Bpage.svelte#L3-L21

**Comment by Snailedlt** [comment]
Nice, thanks! Will keep that in mind for future contributions :)
