### ISSUE TITLE
Disabled option is not rendering

### ISSUE THREAD

**Issue by Angel-Ponce** [janosh/svelte-multiselect#150]
I have a disabled option for example:
```json
{
    "value": "46bf9a93-7e0f-4c5b-abd2-b783e8e31e46",
    "label": "Soporte Técnico 1",
    "jobId": "53491912-86eb-4ee7-a2e2-8ac42710538c",
    "disabled": true
}
```
But in the select this is not rendering.

![image](https://user-images.githubusercontent.com/60164099/200142300-00ccf2a6-6195-4de9-a8e9-255091df2db2.png)

If I change `disabled` prop to `true`, the item is rendered.

**Comment by Angel-Ponce** [comment]
> I have a disabled option for example:
> 
> ```json
> {
>     "value": "46bf9a93-7e0f-4c5b-abd2-b783e8e31e46",
>     "label": "Soporte Técnico 1",
>     "jobId": "53491912-86eb-4ee7-a2e2-8ac42710538c",
>     "disabled": true
> }
> ```
> 
> But in the select this is not rendering.
> 
> ![image](https://user-images.githubusercontent.com/60164099/200142300-00ccf2a6-6195-4de9-a8e9-255091df2db2.png)
> 
> If I change `disabled` prop to `true`, the item is rendered.

Update: 
After I try some times 

The disabled option works only when I specify the `id` and `name` prop

![image](https://user-images.githubusercontent.com/60164099/200142706-6e8b8b96-73e2-4e54-a5e2-b5a57867303d.png)

Before I have'nt an `id` and `name` to my select component

**Comment by janosh** [comment]
I can't repro this. Works as expected in [this REPL](https://svelte.dev/repl/641cc3e5e6f140e7ad8bbba44a52172e?version=3.52.0).

What version are you using?

**Comment by Angel-Ponce** [comment]
I use the version `5.0.6`

Looks that it not work on svelte repl

**Comment by janosh** [comment]
There've been a lot of changes since [v5.0.6](https://github.com/janosh/svelte-multiselect/releases/tag/v5.0.6). Any reason you're on this outdated version?

**Comment by Angel-Ponce** [comment]
No reasons... 
I updated to the latest version and all works...

Thanks for your tome 🤕
