### ISSUE TITLE
FR: option to parse/split JSON stringified selected options to form submission handlers

### ISSUE THREAD

**Issue by lysdexic-audio** [janosh/svelte-multiselect#153]
#152 exposes selected options as JSON stringified arrays - which requires additional/conditional parsing of the FormData object. Conditionally parsing JSON[ is reasonably troublesome](https://stackoverflow.com/questions/3710204/how-to-check-if-a-string-is-a-valid-json-string).

A regular named `<select>` element with the `multiple` attribute will provide separate entries in the FormData object, ie: ` ['regular-select', 'Red'], ['regular-select', 'Green']`

```html
<select multiple name="regular-select" id="regular_select" required>
	<option>Red</option>
	<option>Green</option>
	<option>Blue</option>
</select>
```

Where in 8.02:

`['multiselect, "[\"Green\",\"Blue\",\"Pink\"]"]`

Propose to add logic to separate the entries as the HTML select example above

**Comment by lysdexic-audio** [comment]
I had a quick look at the source and tried a few methods for doing this - but changing the hidden `<input>` element that's currently bound to the selected values to a `<select>` has some issues - and doing some hack with` type=email` is not a good option.

Not going to PR this in - so feel free to close it if you feel it's not worth it 👍

**Comment by janosh** [comment]
Tbh I prefer the `JSON.stringified` output to the split-up array `['regular-select', 'Red'], ['regular-select', 'Green']` that `<select>` pipes into `FormData`. And doing a  `JSON.parse` inside `try/except` doesn't seem that troublesome.

If you disagree there, you could establish a custom rule like all MultiSelect fields will have a prefix of `sms-` in their field `name` or sth like that so that you can tell just be the name if you need to `JSON.parse`.

> Not going to PR this in - so feel free to close it if you feel it's not worth it 👍

We can leave this open for a while and see if anyone else weighs in. Happy to be overruled by popular request.

**Comment by janosh** [comment]
Closing for now as not planned. Anyone feel free to chime in with opinions/use cases.

**Comment by valterkraemer** [comment]
I would also like it to work like a regular `select`. I'm using the fantastic [zod-form-data](https://github.com/airjp73/remix-validated-form/tree/main/packages/zod-form-data) in SvelteKit to validate the forms and now I cannot just pass in the the formData for validation like this:

```ts
const validator = zfd.formData({
  brands: zfd.repeatableOfType(zfd.text()),
});

const formData = await request.formData();

const { success } = validator.safeParse(formData);
```

I've worked around this by modifying the formData for all fields that ends with `$`. This also supports parsing more complex structures.

```ts
const parse$FormData = (formData: FormData) => {
  const newFormData = new FormData();

  const traverse = (path: string, item: unknown) => {
    if (Array.isArray(item)) {
      item.forEach((arrItem, index) => traverse(`${path}[${index}]`, arrItem));
      return;
    }

    if (item?.constructor === Object) {
      Object.entries(item).forEach(([key, value]) =>
        traverse(`${path}${path ? "." : ""}${key}`, value)
      );
      return;
    }

    newFormData.append(path, String(item));
  };

  for (const [key, value] of formData.entries()) {
    if (key.endsWith("$")) {
      const parsed = JSON.parse(value as string);
      const keyTrimmed = key.slice(0, -1);

      traverse(keyTrimmed, parsed);
    } else {
      newFormData.append(key, value);
    }
  }

  return newFormData;
};

const formData = parse$FormData(await request.formData());
```

```ts
[
  { name: 'brands$', value: '["VOLVO","FORD"]' }
  { name: 'special$', value: '[1,{"A": 2}]' }
]
```
becomes
```ts
[
  { name: 'brands[0]', value: 'VOLVO' }]
  { name: 'brands[1]', value: 'FORD' }
  { name: 'special[0]', value: '1' }
  { name: 'special[1].A', value: '2' }
]
```
