### ISSUE TITLE
`MultiSelect received no options` when options is empty due to loading

### ISSUE THREAD

**Issue by Snailedlt** [janosh/svelte-multiselect#154]
Related to #107
We can't use `allowUserOptions` to silence the warning because we don't want users to be able to create their own options.

So I get this error when loading in options asynchronously. Doesn't look like it affects anything, but doesn't look nice with multiple errors every time the page loads. I feel like I should only get this error if `loading` is `false`, however I get it even when loading is true... is this intentional, and if so why?

example code:
```svelte
    let activeRegion: DropdownItem[] = []; 
    let regions: DropdownItem[] = [];

    // regions gets populated in the onMount lifecycle method, through a method with some logic, and a subscription to the $RegionStore

    <MultiSelect
      placeholder="Velg"
      bind:selected={activeRegion}
      options={regions}
      loading={isLoading || regions === undefined || regions.length == 0}
      on:change={handleRegionDropdownChange}
      id="region-multiselect"
      noMatchingOptionsMsg="Ingen treff"
    >
      <span let:option slot="selected" class="selected-multi">
        {option.label}
      </span>
    </MultiSelect>
```

`DropdownItem` is defined as 
```ts
type DropdownItem = { label: string; value: string | number; };
```

**Comment by janosh** [comment]
> I feel like I should only get this error if `loading` is `false`

Agreed, that sounds like more sensible behavior.

**Comment by Snailedlt** [comment]
@janosh Any ETA on the next release? 

A feature we're working on in our project is dependant on this being shipped :)

**Comment by janosh** [comment]
[v8.0.3](https://github.com/janosh/svelte-multiselect/releases/tag/v8.0.3) is out now. 🎉

**Comment by Snailedlt** [comment]
@janosh Thanks! I updated as soon as I saw! :D

However, I noticed we still have one `MultiSelect received no options` exception left. It's because we have a multiselect which is disabled until it gets data. Think it would be a good idea to add `disabled` to the check as well?

Like this: `if (allowUserOptions || loading || disabled) {`

I'll make a PR on the fix in a few min, then you can decide from that :)

**Comment by Gildedter** [comment]
I have a similar issue, my `MultiSelect` is inside an await block that receives the `selected` values, prior  to the `options` _arriving_ and I also have it disabled `onLoad`, so when I enable it and de/select any `option/s` I get the error `"MultiSelect: option with label undefined not found"`
