### ISSUE TITLE
Add `minSelect` and `notRemovable` props

### ISSUE THREAD

**Issue by Snailedlt** [janosh/svelte-multiselect#160]
Would be nice if we could choose the minimum number of options to select. Prettyr much just the opposite of the `maxSelected` prop.
Perhaps it could work together with the required prop? So if a Multiselect is required, you can choose how many options need to be selected.

It would also be nice if we could stop users from removing options (this is needed in our project) through a prop. Maybe the prop can be called `removable`, `notRemovable`, `removableOptions` or `notRemovableOptions`?

**Comment by janosh** [comment]
@Snailedlt I like the idea of allowing `required` prop to be a number to act exactly like a new `minSelect` prop would. I'll add that.

**Comment by Snailedlt** [comment]
@janosh yeah, even better! 😁

But how about the other prop I suggested called `removableOptions`?

**Comment by janosh** [comment]
> But how about the other prop I suggested called `removableOptions`?

Could you open a new issue for that and describe your use case in a bit more detail? That seems more niche.
