### ISSUE TITLE
Typescript linting error `Argument of type 'typeof MultiSelect' is not assignable to parameter of type 'ConstructorOfATypedSvelteComponent'.`

### ISSUE THREAD

**Issue by Snailedlt** [janosh/svelte-multiselect#162]
Doesn't seem to affect anything, but still annoying with those red squiggly lines ;)
```
(alias) class MultiSelect
import MultiSelect
Argument of type 'typeof MultiSelect' is not assignable to parameter of type 'ConstructorOfATypedSvelteComponent'.

Possible causes:
- You use the instance type of a component where you should use the constructor type
- Type definitions are missing for this Svelte Component. If you are using Svelte 3.31+, use SvelteComponentTyped to add a definition:
  import type { SvelteComponentTyped } from "svelte";
  class ComponentName extends SvelteComponentTyped<{propertyName: string;}> {}ts(2345)
  ```
![image](https://user-images.githubusercontent.com/43886029/202406430-9c65ab3a-f479-4ddf-b712-7296802d0e75.png)

**Comment by Snailedlt** [comment]
Not sure why this error pops up, but could ofc be some problem in my local environment

**Comment by janosh** [comment]
Weird. Haven't seen this myself before. Is this happening in every `.svelte` file? Does it depend on what kind of props are passed?

I just noticed that `export let form_input: HTMLInputElement` is missing a default value of `null` and therefore becomes a required prop which was not intended. Maybe related to that.

https://github.com/janosh/svelte-multiselect/blob/b4ad9aa7cdadb81817956da755ed7ff227554142/src/lib/MultiSelect.svelte#L28

**Comment by Snailedlt** [comment]
@janosh hmm, not sure. Oddly enough it just stopped happening all together now. Might have just been a vscode or typescript bug

**Comment by Snailedlt** [comment]
Closing this as solved, since it's no longer an issue (at least for me)
