### ISSUE TITLE
Add prop to disable the remove button next to each selected option

### ISSUE THREAD

**Issue by Snailedlt** [janosh/svelte-multiselect#163]
## What?

Like we discussed in #160, it would be nice if it was possible to prevent users from deleting options beyond a certain point. 

## Case
So in our app, we want there to always be one option selected, but we can't use the new required={1} syntax since we don't submit through a form, and also because we don't want to allow the user to delete the last option in the first place.

This is the multiselect we have in our app:
![image](https://user-images.githubusercontent.com/43886029/202411302-1308f50b-b5c3-49e1-b8fa-3d010edef568.png)
We recently switched from a custom in-house dropdown component, to svelte-multiselect. The custom component we had didn't allow for anything other than 1 selected option, so our logic was built around that. When we changed to svelte-multiselect we noticed bugs and exceptions. So we either have to make the multiselect always have at least one option, change to a \<select\> element and style it extensively, or change the logic to support no selected options (which we don't want to do unless absolutely necessary).

## Prop Name
As for the name of the new prop, I suggest one of the following:
`disableRemoveBtn` : default=false
`hasRemoveBtn`: default=true
`isSelectedOptionsRemovable` default=true
`isSelectedRemovable` default=true

**Comment by Snailedlt** [comment]
I'll make a PR in a few min :)

**Comment by janosh** [comment]
Thanks for explaining the use case in detail. Much clearer now. But `disableRemoveBtn` seems like a rather inflexible and limited API and isn't really what you need. That's what I meant by 'niche' in #160.

Sounds more like what you really want is `minSelect={1}` which is more general in that maybe someone else may want `minSelect={3}`, meaning all remove buttons should disappear if `selected.length <= minSelect`.

That way, `required={3}` can be used if you only care about the component state at form submission time and `minSelect={3}` if you also want to place constraints on intermediate states.

**Comment by Snailedlt** [comment]
Yeah, that seems like a better solution, thanks, I'll update the PR :)
