### ISSUE TITLE
Unable to run `npm run test` locally

### ISSUE THREAD

**Issue by Snailedlt** [janosh/svelte-multiselect#164]
I tried testing the feature I'm implementing in #163 , but when running `npm run test` I get the following error: `No test files found, exiting with code 1`

screenshot:
![image](https://user-images.githubusercontent.com/43886029/202427800-41632402-0a8d-4d4a-8523-2b6edd42db63.png)

text:
```
PS D:\code\svelte-multiselect> npm run test

> svelte-multiselect@8.0.4 test
> vitest --run --coverage tests/unit/*.ts && playwright test tests/*.test.ts


 RUN  v0.25.1 D:/code/svelte-multiselect
      Coverage enabled with c8

filter:  tests/unit/*.ts
include: **/*.{test,spec}.{js,mjs,cjs,ts,mts,cts,jsx,tsx}
exclude:  **/node_modules/**, **/dist/**, **/cypress/**, **/.{idea,git,cache,output,temp}/**, 
**/{karma,rollup,webpack,vite,vitest,jest,ava,babel,nyc,cypress}.config.*
watch exclude:  **/node_modules/**, **/dist/**

No test files found, exiting with code 1
```

**Comment by Snailedlt** [comment]
This is on the `main` branch btw. 

Maybe the cause is a missing config file for playwright and vitest?

**Comment by Snailedlt** [comment]
Changed to `pnpm test` but still getting an error:
![image](https://user-images.githubusercontent.com/43886029/202468421-05ae2540-fe6e-4258-9915-f9e6d5766d40.png)

```
PS D:\code\svelte-multiselect> pnpm test             

> svelte-multiselect@8.0.4 test D:\code\svelte-multiselect
> vitest --run --coverage tests/unit/*.ts && playwright test tests/*.test.ts


 RUN  v0.25.1 D:/code/svelte-multiselect
      Coverage enabled with c8

filter:  tests/unit/*.ts
include: **/*.{test,spec}.{js,mjs,cjs,ts,mts,cts,jsx,tsx}
exclude:  **/node_modules/**, **/dist/**, **/cypress/**, **/.{idea,git,cache,output,temp}/**, 
**/{karma,rollup,webpack,vite,vitest,jest,ava,babel,nyc,cypress}.config.*
watch exclude:  **/node_modules/**, **/dist/**

No test files found, exiting with code 1
 ELIFECYCLE  Test failed. See above for more details.
 ```

**Comment by janosh** [comment]
Maybe this is a Windows issue? Does it work if you replace backward with forward slashes?

```sh
vitest --run --coverage tests\unit\*.ts && playwright test tests\*.test.ts

**Comment by Snailedlt** [comment]
@janosh Nope, that caused an escape character error, so I tried to escape the backslashes, but I get the same error.

I tried the following to no avail:
`vitest --run --coverage tests\unit\*.ts && playwright test tests\*.test.ts`
`vitest --run --coverage tests\\unit\\*.ts && playwright test tests\\*.test.ts`
`vitest --run --coverage ./tests/unit/*.ts && playwright test tests/*.test.ts`

**Comment by janosh** [comment]
What about quoting the paths? Maybe it's a shell expansion issue.

```sh
vitest --run --coverage 'tests/unit/*.ts' && 'playwright test tests/*.test.ts'
```

**Comment by janosh** [comment]
Closing this as resolved assuming it was a shell expansion issue. Feel free to reopen if not.
