### ISSUE TITLE
Website isn't showing rust icon

### ISSUE THREAD

**Issue by Snailedlt** [janosh/svelte-multiselect#173]
Rust icon isn't showing because devicons doesn't have an `original` version of the icon. It only has a `plain` version. 

This is a mishap in the devicon repo, and shouldn't happen, since `original` is prioritized over `plain` as a name if the same icon can be used as multiple versions. See [aliases and AliasObj](https://github.com/devicons/devicon/wiki/Updating-%60devicon.json%60#aliases-and-aliasobj)

I'll make an issue to fix this in the next major version of devicon.
![image](https://user-images.githubusercontent.com/43886029/203033582-a1e338be-f9cc-45fe-941b-14718ac095f5.png)

![image](https://user-images.githubusercontent.com/43886029/203033569-d4fc859c-7c3f-4d86-b531-0d486ad313db.png)

## Repro

The issue is live in production here: https://janosh.github.io/svelte-multiselect/

## Expected behavior

Rust icon shows

## Additional context

A quick fix could be to just temporarily remove Rust from the list of languages. A better fix would be to first check if the `original` version exists, then if it doesn't check `plain` versions and lastly `line` version.

Note that devicon also has wordmark versions for a few icons: Here's an overview on all [SVG Versions](https://github.com/devicons/devicon/wiki/SVG-Versions) in devicon

**Comment by janosh** [comment]
Thanks for reporting. I had noticed that as well and opening an issue with devicon was on my to do list. Thanks for taking care of that!

**Comment by janosh** [comment]
I'll leave this issue open until the next major release. The LanguageSlot component is meant to handle missing icons so not that urgent.

**Comment by janosh** [comment]
@Snailedlt Is there an ETA on the next devicon release?

**Comment by Snailedlt** [comment]
Hopefully sometime in January

**Comment by janosh** [comment]
@Snailedlt Is a `devicon` release still in the works?

**Comment by Snailedlt** [comment]
> @Snailedlt Is a `devicon` release still in the works?

Yeah, delay after delay due to lots of workflow changes and other big changes breaking stuff.

I'm on vacation atm, but hopefully some of the other maintainers can make a release in my absense.

**Comment by Snailedlt** [comment]
This should be fixed now :)

**Comment by janosh** [comment]
thanks for the update!
