### ISSUE TITLE
Update link to website on NPM

### ISSUE THREAD

**Issue by Snailedlt** [janosh/svelte-multiselect#177]
The link to the website is outdated on NPM: https://www.npmjs.com/package/svelte-multiselect
![image](https://user-images.githubusercontent.com/43886029/203974798-b2394dfa-b511-4677-9a6a-55d6c0ccc261.png)

Should be updated to: https://janosh.github.io/svelte-multiselect

**Comment by janosh** [comment]
It's already updated actually:

https://github.com/janosh/svelte-multiselect/blob/2e88108a35d75f88b1a6e754caf338600de16e07/package.json#L5

Just needs a new release to be reflected on NPM.

Note there are unresolved navigation issues with the GitHub Pages deployment (tracked over at https://github.com/sveltejs/kit/issues/7742). I may have jumped the gun a little here with moving away from Netlify.
