### ISSUE TITLE
Add CHANGELOG.md

### ISSUE THREAD

**Issue by Snailedlt** [janosh/svelte-multiselect#179]
A changelog is very useful for quickly catching up on changes especially across multiple releases. Dependabot will automatically show a link and preview of the changelog as well.

The reason I prefer a changelog over release notes is simply because I can see all of the changes in a single file, which makes it quicker and easier to check changes for multiple releases

## Example

https://github.com/rollup/plugins/blob/master/packages/typescript/CHANGELOG.md

![image](https://user-images.githubusercontent.com/43886029/204778608-8ca64d3b-1508-40eb-88de-c48917c8da7d.png)

**Comment by janosh** [comment]
I agree a changelog is useful. I'll add one.

Looks like this will require some `git surgery` though as I'd like the changelog to be auto-generated and some commits contain typos, repeated spaces, etc. which are caught by the commit hooks in https://github.com/janosh/svelte-multiselect/blob/main/.pre-commit-config.yaml. This will affect open PRs like #175 which will have to be rebased to fix divergent history.

**Comment by janosh** [comment]
Actually maybe git surgery is not necessary. Looks like I could combine `--prepend` and `--unreleased-only` from https://github.com/cookpete/auto-changelog#usage to auto-generate changelog but leave typo fixes to existing changelog in place.
