### ISSUE TITLE
Scrolling is not working as expected

### ISSUE THREAD

**Issue by sacarvy** [janosh/svelte-multiselect#18]
For reference :- 😶‍🌫️
https://user-images.githubusercontent.com/69889565/146889350-baf55173-e71b-4eed-b4c8-ec1f85088729.mp4

This might be because of focus get blur when click on scroll-bar

**Comment by janosh** [comment]
Thanks for reporting. Correct diagnosis too. 👍

**Comment by janosh** [comment]
This is fixed in [v2.0.0](https://www.npmjs.com/package/svelte-multiselect/v/2.0.0). Note that this new major version also includes breaking changes, mainly that `bind:selected` now returns objects instead of strings. To get the strings as before, use `bind:selectedLabels` instead.
