### ISSUE TITLE
 allowUserOptions breaks option selection via keyboard

### ISSUE THREAD

**Issue by wylfen** [janosh/svelte-multiselect#183]
If the component has `allowUserOptions` set and the user has entered some input, matching options are no longer selectable via the arrow keys. Instead, the cursor only jumps to the beginning or end of the input, depending on which key was pressed.

This is easily reproducible for me (Firefox 107.0.1) on the demo page with the "Slot Components" example:

1. Focus the multiselect component
2. Hit up/down arrow; options are selectable
3. Type a character, for example "g"
4. The options narrow down
5. Hit up/down arrow; options are no longer selectable via the keyboard

**Comment by janosh** [comment]
Good catch! Thanks for reporting.

Fix and new release incoming.
