### ISSUE TITLE
Styling: enable hiding or disabling the `ExpandIcon`

### ISSUE THREAD

**Issue by joelmukuthu** [janosh/svelte-multiselect#185]
This one: https://github.com/janosh/svelte-multiselect/blob/70cd62bb52eb9dde55997c2ed1a6b22f405d7029/src/lib/MultiSelect.svelte#L398

I can currently work around this by adding global CSS:

```css
:global(.multiselect > svg) {
  display: none;
}
```

But that's not a future-proof selector. 

Since other users might want to customise the icon instead, I think it'd be best to fix this by wrapping the icon in a slot, which would also allow me to hide it by passing some empty fragment for the slot. That said, it could probably also be fixed by adding a CSS variable for the SVG's display or by adding a class to the SVG (which IMO is the least ideal as it forces global CSS on the consumer)

**Comment by janosh** [comment]
Excellent suggestion! Like you said, a new slot to wrap the default expand icon is the best option here. PR incoming.
