### ISSUE TITLE
Ajax support (dynamic list of options based on search)

### ISSUE THREAD

**Issue by ul8** [janosh/svelte-multiselect#192]
Any plans for this? (see https://vue-select.org/guide/ajax.html for an example of what I mean).

My use case: A gigantic list of options that I don't want to load into the component - it would be better to only load matches when searching.

I like the minimal approach by vue-select (i. e. no actual ajax/fetch support, it just provides a hook that users can implement as needed)

Thanks!

**Comment by janosh** [comment]
@ul8 `svelte-multiselect` offers a very similar API. You do the actual fetching of options in a parent component and just tell MultiSelect to show a loading spinner while that's in progress. The relevant props are called `loading` and `searchText` which you can both bind to. There's an example on the [demo site](https://multiselect.janosh.dev) and a [Svelte REPL](https://svelte.dev/repl/79e22e1905c94456aa21564b4d5f8759) how you might perform a fetch request on user-input to get matching options from a database:

```svelte
<script lang="ts">
  import MultiSelect from 'svelte-multiselect'

  let value
  let searchText = ''
  let loading = false
  let options = ['list', 'of', 'options']
  $: if (searchText) {
    loading = true
    setTimeout(async () => {
      // perform some fetch/database request here to get list of options matching searchText
      // options = await fetch(`https://example.com?search=${searchText}`)
      loading = false
    }, 1000)
  }
</script>

<pre>value = {JSON.stringify(value)}</pre>

<MultiSelect
  bind:options
  bind:value
  bind:searchText
  {loading}
/>
```

Please re-open if you encounter any issues.

**Comment by ul8** [comment]
Thans @janosh, somehow I did not find this when I read the docs :)

**Comment by ul8** [comment]
Hey @janosh this works as you described, thanks! Just a few "cosmetic" issues:
a) in this use case, I want to not load any options until search terms are entered. This prints an error message to the console:
"MultiSelect received no options"
b) When I add options via the search, then delete them again, I get another console error message.

![Screenshot_2023-01-18_wOlBOH10](https://user-images.githubusercontent.com/589744/213108213-07f420d7-90cf-48d5-9d0f-f7b3edefcddf.gif)

Any way these error messages can be disabled?

**Comment by janosh** [comment]
Yes, there's a prop called `allowUserOptions` which you can set to `true` or `'append'` to make the error disappear. Multiselect won't complain about missing option if users are expected to create their own. In your case, it sounds like you don't really want users to be able to enter custom options though. A better solution might be a new prop `onError: 'error' | 'warn' | 'ignore'`. Happy to solicit feedback on that.

**Comment by ul8** [comment]
Thanks @janosh, I had seen that prop but as you say it doesn't fit my use case. 

The new prop you suggested sounds great. I assume both the errors I saw would be categorized as warnings so I could switch this to "error" only in production.

**Comment by ul8** [comment]
@janosh yes that should work but doesn't take care of the second error message (see my video above)

**Comment by janosh** [comment]
@ul8 Thanks for pointing out the 2nd error. Hadn't noticed it first time around. I just tried but couldn't reproduce it. Could you open a new issue with a repro? I'll go ahead and merge #198 for now.
