### ISSUE TITLE
Subscribing to Enter key events

### ISSUE THREAD

**Issue by heck-gd** [janosh/svelte-multiselect#193]
I have a multiselect that is made up entirely of user values, like so:
```
<MultiSelect options={[]} bind:selected={filter.values} allowUserOptions={true} />
```

Once the user has added all desired options into the select, I want it to be possible to submit the filter request using the Enter key.

However, I couldn't find a way to get notified of such key presses **only** when the `searchText` is empty - essentially, when there are one or more "finished" options present in the select with a blinking cursor at the end and the dropdown being closed (at least visibly).

I tried using a keydown event and bound a bool to `open`, however that bool is always `true` when the input has focus, so I would get spurious Enter key events whenever a new option is created, etc.

Is there a way to make this work? It seems like a pretty basic/common thing, so I probably missed something obvious.

**Comment by janosh** [comment]
@heck-gd I'm not sure I understand your question correctly. Could you explain what you mean by "submit the filter request"?

Just guessing here but maybe [this REPL](https://svelte.dev/repl/a8f6388fe688467b81fb830b6fa68745?version=3.55.0) does what you want?

```svelte
<script>
  import MultiSelect from 'svelte-multiselect'

  const options = [`Svelte`, `React`, `Vue`, `Angular`, `...`]

  let selected = []
  let searchText
  function key_handler(event) {
    if ([`Enter`].includes(event.code) && searchText == '') {
      console.log('hi')
    }
  }
</script>

<pre>
  <code>selected = {JSON.stringify(selected)}</code>
</pre>

<MultiSelect {options} bind:selected on:keydown={key_handler} bind:searchText />
```

**Comment by heck-gd** [comment]
> I'm not sure I understand your question correctly. Could you explain what you mean by "submit the filter request"?

Sorry, that was a bit obscure. I mean doing something with the selected items, such as logging them or sending them to a server.

> Just guessing here but maybe [this REPL](https://svelte.dev/repl/a8f6388fe688467b81fb830b6fa68745?version=3.55.0) does what you want?

Yes, that's almost a repro. Here's one that more closely resembles my case: [REPL](https://svelte.dev/repl/fbd1ad12a81b4ce79d51063c58c81e4b?version=3.55.0)
Enter `asd`, press Enter to create the option (notice how `hi` is logged because multiselect's handler is executed first and clears `searchText`), press Enter again. This second Enter is the only one I want to handle.

**Comment by janosh** [comment]
> Yes, that's almost a repro. Here's one that more closely resembles my case: [REPL]

Ah, now I understand your problem. Wasn't even aware `searchText` is reset to empty string before any key handlers can fire.

Admittedly, it's very clunky but a workaround would be to set `resetFilterOnAdd={false}` and then to manually reset `searchText` in the key handler. Haven't thought carefully about this though. Might have some unintended usability implications. Here's the [updated REPL](https://svelte.dev/repl/a8f6388fe688467b81fb830b6fa68745).

```svelte
<script>
  import MultiSelect from '$lib'

  const options = []

  let selected = []
  let searchText
  function key_handler(event) {
    if (event.code == `Enter` && selected.length > 0) {
      if (searchText.length == 0) {
        console.log(`hi`)
      } else {
        searchText = ``
      }
    }
  }
</script>

<pre>
  <code>selected = {JSON.stringify(selected)}</code>
</pre>

<MultiSelect
  {options}
  bind:selected
  on:keydown={key_handler}
  bind:searchText
  allowUserOptions
  resetFilterOnAdd={false}
/>
```

**Comment by heck-gd** [comment]
Thanks, that works! Yeah, it's a bit clunky, but I wasn't able to notice any adverse effects while playing around with it a bit, so I'll roll with it.
