### ISSUE TITLE
Changing `bind:value` does not update MultiSelect

### ISSUE THREAD

**Issue by danhk0612** [janosh/svelte-multiselect#194]
My code in body is this.
```
<MultiSelect bind:value={addItemObj.more_singers} options={[]} allowUserOptions="append" />
```

As far as creating a multiselect and selecting an item, it works fine.

```
addItemObj.more_singers = []
```

However, if the bound array value is changed to an empty array, it is not reflected in the multiselect.

is this an error? Or is there another way I'm not aware of?

**Comment by janosh** [comment]
This is expected. There's a warning in the readme that `value` only supports 1-way binding. It's intended for use with `maxSelect={1}`.

> 1. ```ts
>    value: Option | Option[] | null = null
>    ```
> 
>    If `maxSelect={1}`, `value` will be the single item in `selected` (or `null` if `selected` is empty). If `maxSelect != 1`, `maxSelect` and `selected` are equal. Warning: `value` supports 1-way binding only, meaning `bind:value` will update `value` when internal component state changes but changing `value` externally will not update internal component state. This is because `value` is already reactive to `selected` and making `selected` reactive to `value` would be cyclic. Suggestions for better solutions that solve both [#86](https://github.com/janosh/svelte-multiselect/issues/86) and [#136](https://github.com/janosh/svelte-multiselect/issues/136) welcome!

 Since you don't use `maxSelect`, you could try replacing `bind:value` with `bind:selected`.

**Comment by danhk0612** [comment]
Oh, something I missed by using bind:value in general.
thank you for telling me.
