### ISSUE TITLE
Clearing options results in error message (but everything works as intended)

### ISSUE THREAD

**Issue by ul8** [janosh/svelte-multiselect#203]
I'm using the component as a search input as discussed in #192.

When I select an item, then delete it, I get the console error 
`MultiSelect: option with label list not found`

## Repro

https://svelte.dev/repl/1bb172026c944cedab4bb7a6271f477a?version=3.55.1

1. type "list" into the select
2. select the item
3. delete it again
4. check the console

## Expected behavior

In this context, it's not really an error - so no need for a console error.

**Comment by ul8** [comment]
The obvious "cause" of this issue is of course on line 15. I like what that line does though :) So I hope you can add some logic to not show an error if we just deleted something.

**Comment by janosh** [comment]
@ul8 Thanks for the repro!

This actually led me to find a poor implementation choice in the `remove(option)` function. Fix inbound.

**Comment by janosh** [comment]
Fix released in [v8.3.0](https://github.com/janosh/svelte-multiselect/releases/tag/v8.3.0).
