### ISSUE TITLE
Improvement: Add an option to select the first item by default when pressing Enter

### ISSUE THREAD

**Issue by gschurck** [janosh/svelte-multiselect#205]
Improvement suggestion : 
 
To make svelte-multiselect really Keyboard-friendly, it would be useful to add an option to select the first item in list by default when pressing Enter during search. So no need to use the arrow keys to select the good item, and it's faster to add multiples items imo, such as [this library](https://svelte-select-examples.vercel.app/examples) :

![Screenshot_20230212_154258](https://user-images.githubusercontent.com/21091232/218317808-2e1d0bfb-ba54-4f9e-ae69-dd39198d957e.png)

**Comment by janosh** [comment]
Thanks for the issue. That's a great suggestion and easily implemented by making the first matching option active on any keypress if no other special cases apply (like deleting the last selected option on backspace).

**Comment by gschurck** [comment]
Nice, thank you for your quick response.
