### ISSUE TITLE
Event removeAll fires before selected items have been removed

### ISSUE THREAD

**Issue by erik-dickens** [janosh/svelte-multiselect#208]
Hi and thanks for a nice component!
I have a question and potentially a bug;  when the removeAll event is fired the selected items (in the `selected` attribute) haven't been removed. In comparison, when the add or remove-event fires the added/removed item has already been removed (which seems reasonable). Bug?
In the code below, the bounded `tagsFilter` will still contain all the removed items when clicked on `removeAll`.
 
```svelte
let tagsFilter: string[]
...
<MultiSelect
  bind:selected={tagsFilter}
  ...
  on:remove={() => console.log('remove', tagsFilter)}
  on:removeAll={() => console.log('removeAll', tagsFilter)}
/>
```

**Comment by janosh** [comment]
Thanks for reporting. I can see how this could be unexpected behavior. Should be a simple change.

**Comment by erik-dickens** [comment]
Thanks for fast reply and implementation!
