### ISSUE TITLE
A11y: The attribute 'aria-selected' is not supported by the role 'listitem'

### ISSUE THREAD

**Issue by shadowempire123** [janosh/svelte-multiselect#213]
...
"svelte-multiselect": "^8.5.0"
"@azure/msal-browser": "^2.34.0",
"@beyonk/svelte-datepicker": "^12.0.1",
"@popperjs/core": "^2.11.6",
"@skeletonlabs/skeleton": "^1.0.0",
"@sveltejs/adapter-auto": "^2.0.0",
"@sveltejs/kit": "^1.11.0",
"@tailwindcss/forms": "^0.5.3",
"autoprefixer": "^10.4.14",
"classnames": "^2.3.2",
"flowbite": "^1.6.4",
"flowbite-svelte": "^0.32.1",
"postcss": "^8.4.21",
"prettier": "^2.8.4",
"prettier-plugin-svelte": "^2.9.0",
"svelte": "^3.56.0",
"svelte-multiselect": "^8.5.0",
"svelte-preprocess": "^5.0.1",
"tailwindcss": "^3.2.7",
"vite": "^4.1.4"
...
import MultiSelect from 'svelte-multiselect'
...

<MultiSelect
	--sms-options-bg="white"
	--sms-text-color="gray"
	bind:selected={oTComponent}
	id="multiselect-components"
	options={componentItems}
	placeholder="Select the component(s)"
/>

**Comment by janosh** [comment]
This was already fixed by @RyanZhiNie in #211. I'll cut a new release with TS v5 soon.
