### ISSUE TITLE
Add ability to control selected items through selected{Labels,Values}

### ISSUE THREAD

**Issue by janosh** [janosh/svelte-multiselect#22]
#13 resulted in the suboptimal situation that if you're only interested in primitive labels/values for the selected items, you can get those through

```svelte
<MultiSelect bind:selectedLabels bind:selectedValues />
```

but it's no longer a two-way binding. You cannot control the component's internal `selected` array through those props since they are reactive to `selected` internally:

```svelte
$: selectedLabels = selected.map((op) => op.label)
$: selectedValues = selected.map((op) => op.value)
```

Need to figure out how to allow users to reverse this dependence and set `bind:selectedLabels/Values` as the source of truth.

**Comment by VikingC0der** [comment]
Could you please help me understand correctly. does this issue mean that one is unable to pre-populate the MultiSelect?
I am running into an issue where I cant figure out how to have pre-selected options in the MultiSelect on a form where the user is meant to edit an entry. I dont know if I am doing it incorrectly or if the MultiSelect is unable to do this

**Comment by janosh** [comment]
@VikingC0der If you're passing your options as objects, you can set `preselected: true` on them:

https://github.com/janosh/svelte-multiselect/blob/af009b56048bc94d2514ab316e669c2896f61b65/src/lib/index.ts#L8-L12

Or, if you're just passing strings as options, you can `bind` to `selected` and initialize it to a non-empty array of objects:

```svelte
<script lang="ts">
  const mlFrameworks = [
    `TensorFlow`, `PyTorch`, `scikit-learn`, `Spark ML`, `Torch`, `Huggingface`, `Keras`, `Caffe`, `Theano`, `CNTK`,
  ]
  let selectedML = [{ label: `PyTorch`, value: `PyTorch` }]
</script>

<MultiSelect
  options={mlFrameworks}
  bind:selected={selectedML}
/>
```

**Comment by VikingC0der** [comment]
There was a huge delay before I could come back to this but your guidance solved my problem. Thank you for the help.

**Comment by GodPingu** [comment]
Recently ran into this. The simplex fix (maybe not optimal) imo would be to export the remove and add function this would allow the multiselect component to be bound to a variable which can then be used to add/remove selections

**Comment by janosh** [comment]
@GodPingu Interesting suggestion. Exporting functions not as props but for binding to and then using externally is not a very common pattern afaik. Not sure if has any downsides but could be worth exploring. Looks like your PR #73 takes the approach described above though which maybe is the more user friendly approach in any case?
