### ISSUE TITLE
Form validation example

### ISSUE THREAD

**Issue by janosh** [janosh/svelte-multiselect#23]
Add an example to the docs how to hook `svelte-multiselect` up to [`svelte-use-form`](https://github.com/noahsalvi/svelte-use-form) incl. validation.

**Comment by egdegauperaa** [comment]
Hi @janosh, how do I go about contributing code if I wanted to? With regards to the id - issue yesterday, I tried to pull main, create a branch and then push it. I was then going to create a pull request, but wasn´t allowed to push the branch (403 error). Do I have to be a project member?

**Comment by janosh** [comment]
@egdegauperaa To push directly to a repository, yes you would have to be added as a collaborator. The usual workflow in open source is to fork the repository, push your branch to that and then open a pull request from your fork to the upstream repo for review by maintainer(s).
