### ISSUE TITLE
[svelte-check] Cannot find module 'svelte-multiselect' or its corresponding type declarations.

### ISSUE THREAD

**Issue by tbydza** [janosh/svelte-multiselect#233]
Hello,
I have problems using this library after update to version >= [v8.4.0](https://github.com/janosh/svelte-multiselect/releases/tag/v8.4.0)

```svelte
<script lang="ts">
    import type {Option} from 'svelte-multiselect';
    import MultiSelect from 'svelte-multiselect';

    const opts: Option[] = [1, 2, 3, 4, 5]
</script>


<div class="test">
    This is just a test
</div>
<MultiSelect options={opts}></MultiSelect>
```
When I import from `svelte-multiselect`, svelte-check will throw error: `Cannot find module 'svelte-multiselect' or its corresponding type declarations.`.  Build is ok, code works, only svelte-check is the problem.

I found this svelte/package v2 issue [here](https://github.com/sveltejs/kit/issues/9114).
Did you managed to solve it? Or is it svelte-check issue and I should create issue there?

**Comment by janosh** [comment]
The recommended fix is to update to TypeScript v5 and set `"moduleResolution": "bundler"`. Let me know if that doesn't fix the issue or if something prevents you from upgrading.

**Comment by tbydza** [comment]
I already upgraded to TS v5 with `"moduleResolution": "bundler"`. 
But I found the issue, I am using multiple tsconfig files and svelte-check was using the the wrong tsconfig without `"moduleResolution": "bundler"`. After I've fixed svelte-check parameters, it is working without problem.
Anyway, thank you for your help and sorry to bother you.
