### ISSUE TITLE
Disable search input prop...

### ISSUE THREAD

**Issue by shanestreator** [janosh/svelte-multiselect#237]
Is there a prop I may not be seeing to disable the search input focus/functionality?

**Comment by janosh** [comment]
Could you be more specific? Are you asking about [disabling the whole component](https://multiselect.janosh.dev/disabled)?  Or just disabling tabbing the component into focus?

**Comment by shanestreator** [comment]
Just disabling the input search functionality. Everything else would function the same.

I'm running into an issue with mobile UX where - when the input field is focused (search functionality) the native keyboard overlays the dropdown select options and the window for selecting options is reduced by 50% (in addition to header/browser bar).

If a prop like `disableSearch=true` would conditionally display the dropdown, without search, it should fix the issue.

![Screenshot_20230613-155603_Chrome](https://github.com/janosh/svelte-multiselect/assets/35476261/18c16e37-bf8d-4abe-87cb-62cd2f4851bd)

**Comment by janosh** [comment]
@shanestreator Thanks for the details. What you need can already be achieved by passing `inputmode="none"` to Multiselect. I modified your PR #239 to document this in the readme.

**Comment by shanestreator** [comment]
Interesting, that seems to work as expected, thanks!
According to MDN `inputmode="none"` is not supported by Safari but just tested and seems to work as well.

**Comment by janosh** [comment]
I think you were looking at Desktop Safari. MDN documents Mobile Safari as having support.

![Screenshot 2023-06-18 at 15 07 41](https://github.com/janosh/svelte-multiselect/assets/30958850/f0679fe1-52c4-44bc-a95c-feb41cca3c82)

**Comment by shanestreator** [comment]
Jeez, I might be blind. 😳

**Comment by janosh** [comment]
No worries, happens to me all the time. 😄
