### ISSUE TITLE
[bug] A recent change to the library seems to be causing a build error

### ISSUE THREAD

**Issue by Snailedlt** [janosh/svelte-multiselect#24]
Looks like [these lines](https://github.com/janosh/svelte-multiselect/blame/main/src/lib/MultiSelect.svelte#:~:text=%7B%40const%20%7B%20label%2C%20disabled,disabledTitle%20%3D%20defaultDisabledTitle%20%7D%20%3D%20option%7D) are causing it. 

```svelte
[!] (plugin svelte) ParseError: Unexpected character '@'
node_modules\svelte-multiselect\MultiSelect.svelte
266:     >
267:       {#each matchingOptions as option, idx}
268:         {@const { label, disabled, title = null, selectedTitle } = option}
              ^
269:         {@const { disabledTitle = defaultDisabledTitle } = option}
270:         <li
ParseError: Unexpected character '@'
```
![image](https://user-images.githubusercontent.com/43886029/151130784-49c240b4-ce05-4712-bbdc-b6d5682abd67.png)

**Sidenote:**
I've never seen @const before, is it dependant on some external library to work?

**Comment by janosh** [comment]
It's a very new Svelte feature added in [v3.46.0](https://github.com/sveltejs/svelte/blob/master/CHANGELOG.md#3460). So the easiest fix is to update your Svelte version.

**Comment by Snailedlt** [comment]
Thanks. 
You should update the description somewhere to specify what minimum Svelte version is required

**Comment by Snailedlt** [comment]
Can confirm it works with latest svelte version btw :)

**Comment by janosh** [comment]
It's in `package.json` but people don't usually look there

https://github.com/janosh/svelte-multiselect/blob/3bca149baa3153f3cb03c8cafdee24094d9848c2/package.json#L33

so I'm open to adding it to the readme. Do you a badge or a text note would be better?

![npm dev dependency version](https://img.shields.io/npm/dependency-version/svelte-multiselect/dev/svelte)

```md
![npm dev dependency version](https://img.shields.io/npm/dependency-version/svelte-multiselect/dev/svelte)
```

**Comment by Snailedlt** [comment]
Yeah, it should be in the `README.md` too. 

Maybe a new chapter for dependencies? If so, you can add them like this

## Dependencies
- "svelte": "^3.46.2"
- "some-other-dependency":"^1.0.0"

A badge would work too. 


The main thing for me is it should be searchable (which it hopefully is now because of this issue).

**Comment by janosh** [comment]
I'll go with it a batch for now since that doesn't require manual maintenance when the minimum version number changes.
