### ISSUE TITLE
Support in Typescript

### ISSUE THREAD

**Issue by keanesnow98** [janosh/svelte-multiselect#244]
Hi, I'd like this svelte select2 module, but the problem is: I am using Typescript.
But I cannot find Defined Typed module in npm.
Is there any way to use it in Typescript?

**Comment by janosh** [comment]
I'm not sure I understand the question. This package ships with type declarations as you can see by clicking into the `dist/` folder in the [NPM code tab](https://npmjs.com/package/svelte-multiselect/v/9.0.0?activeTab=code). So TypeScript support comes out of the box.

**Comment by keanesnow98** [comment]
Can you help me with this error?
![image](https://github.com/janosh/svelte-multiselect/assets/119104736/ce527256-f291-4494-81ba-725483e3e63c)

**Comment by janosh** [comment]
Please post your TS and Multiselect versions and your `tsconfig.json`.

**Comment by keanesnow98** [comment]
I am using npm installed typescript version 5.1.3.
And I have just installed 'svelte-multiselect' version 9.0.0.

My tsconfig.json file is:
```
{
	"extends": "./.svelte-kit/tsconfig.json",
	"compilerOptions": {
		"allowJs": true,
		"checkJs": true,
		"esModuleInterop": true,
		"forceConsistentCasingInFileNames": true,
		"resolveJsonModule": true,
		"skipLibCheck": true,
		"sourceMap": true,
		"strict": true,
		"ignoreDeprecations": "5.0",
		"importsNotUsedAsValues": "error",
		"outDir": "./dist"
	}
	// Path aliases are handled by https://kit.svelte.dev/docs/configuration#alias
	//
	// If you want to overwrite includes/excludes, make sure to copy over the relevant includes/excludes
	// from the referenced tsconfig.json - TypeScript does not merge them in
}
```

**Comment by janosh** [comment]
Try adding `"moduleResolution": "bundler"`. I recommend adding that to all your TS 5 Svelte projects.

```json5
{
  "extends": "./.svelte-kit/tsconfig.json",
  "compilerOptions": {
    // ...
    "moduleResolution": "bundler",
  }
}

**Comment by keanesnow98** [comment]
Cool. It's like magic.
Thanks for you help!
