### ISSUE TITLE
How to make 2 way binding value[]<->options[] ?

### ISSUE THREAD

**Issue by michaltaberski** [janosh/svelte-multiselect#249]
I would like to keep 2 way binding with making mapping on the way. This is not pure `svelte-multiselect` issue, but it's easy to visualise it in the `svelte-multiselect` usecase:

I would like to use `values` as an array of strings (ids) and dynamically map those ids to provided options (if present). It's not a problem doing this 1-way, but how to maintain the 2-way binding?

```svelte
// Superior component 
<script lang="ts">
  import MultiSelect from "svelte-multiselect";
  import { ExcludeFalsy } from "../typeScriptUtils";

  type Option = { label: string; value: string };

  export let values: string[];
  export let options: Option[] = [];

  $: {
   selected = values
    .map((val) => options.find(({ value }) => val === value))
    .filter(ExcludeFalsy);
   // OFC THIS IS NOT POSSBILE (CIRCULAR UPDATE), BUT HOW TO DO THING LIKE THAT?
   // values = selected.map(({ value }) => value);
  }
</script>

<MultiSelect {options} bind:selected />
```

**Comment by janosh** [comment]
I only have bad news on this point. I'm not aware of a solution and I'm not even sure there _is_ a way the break the recursion in the general case.

**Comment by michaltaberski** [comment]
I have a little update that might be useful for others. [Stackoverflow has helped me a bit](https://stackoverflow.com/questions/72407572/idiomatic-way-in-svelte-to-do-two-way-binding-with-an-intermediate-transformatio). It does the job, although it is a little bit complicated.  Nevertheless for now it's good enough. 

Thanks @janosh for feedback.

**Comment by janosh** [comment]
Wow, that's a [very cool REPL](https://svelte.dev/repl/fce6e30f34ee49c1b9674731dc40b395)! I had no idea this was possible. Thanks for sharing. I'll definitely use this to make `value` and `selected` each reactive to the other. 👍
