### ISSUE TITLE
Add prop to give input an id

### ISSUE THREAD

**Issue by egdegauperaa** [janosh/svelte-multiselect#25]
Apologies if this is already possible: I´d like to give the input tag an id to be able to associate a label with it (accessibility-related). I tried to pull main, create a branch, do the changes and push it to the repository to then create a PR, but getting a 403 error. Anyway, I´m suggesting adding a prop "inputId" to MultiSelect.svelte and using it on line 254:
`id={inputId}`

**Comment by janosh** [comment]
I was thinking about that use case too. Seems much more important than being able to add an `id` to the outer wrapper `div`. Not sure why I set it up that way in the first place but I'm guessing nobody uses this feature so we may as well apply the `id` to the `<input>` element instead even though it's strictly speaking a breaking change. Whatever, Svelte people can handle breaking changes. 😄

**Comment by janosh** [comment]
Released in v.3.2.0.

**Comment by janosh** [comment]
Just for future reference for myself, [here are the MDN docs on form label a11y](https://developer.mozilla.org/en-US/docs/Web/Accessibility/Understanding_WCAG/Text_labels_and_names#form_elements_must_be_labeled).
