### ISSUE TITLE
When allowUserOptions={true} user can't enter custom option if it is a substring of an existing option

### ISSUE THREAD

**Issue by paul-brenner** [janosh/svelte-multiselect#253]
For the first example on https://multiselect.janosh.dev/allow-user-options if I wanted to enter that my favorite fruit is actually a "blue" or a "straw"... oh those aren't real fruits better example: "berry". Any of these three, if I type them in then hit enter it will select the option that exists in the drop down. So typing "berry" and hitting enter selects Strawberry even though perhaps I really wanted to enter just "berry".

My real example came from a list of doctors where I learned that "ENT" actually exists in "dentist". So in my example the user typed in ENT, couldn't hit enter since it would select dentist, so clicked out of the box which just leaves the ENT text sitting there looking like it is ok. On form submission no data comes through.

**Comment by janosh** [comment]
Good catch. I'd noticed this too a while back and meant to fix but forgot about it. Thanks for the reminder.

**Comment by paul-brenner** [comment]
This looks like it solves my issue. Thanks!
