### ISSUE TITLE
Request textDocument/hover failed. Code: -32603 

### ISSUE THREAD

**Issue by kobe-ra** [janosh/svelte-multiselect#256]
I just started using this library, imported it and placed the element in component like this

```
<MultiSelect bind:selected {options} maxSelect={1} outerDivClass="" />
```

Now anytime I hover over this element or change its value I'm getting Svelte intellisense error:

```
[Error - 8:13:53 PM] Request textDocument/hover failed.
  Message: Request textDocument/hover failed with message: EISDIR: illegal operation on a directory, read
  Code: -32603 
```

Also the hover over element's props work, so I don't know what causes this error.

It's especially annoying because it takes my focus from terminal window in vscode to output window.

My setup is Laravel-Inertiajs-Svelte and this didn't occur with any other package.

**Comment by janosh** [comment]
Very strange. Have never seen something like that. `svelte-multiselect` doesn't perform any file IO so not sure how

```
EISDIR: illegal operation on a directory
```

could be triggered. Do you have code to upload/download files that might cause this? Can you repro this in a REPL? If so, would help with debugging if I can see it myself.

**Comment by kobe-ra** [comment]
I cannot get svelte-intellisense into the sveltelab.dev, therefore cannot reproduce. I'll just live with it I guess. Thanks.

**Comment by janosh** [comment]
Do you have a link to the repo?
