### ISSUE TITLE
The where classes are overwriting the classes I am giving through props.

### ISSUE THREAD

**Issue by AchalS-iglu** [janosh/svelte-multiselect#259]
The where classes are overwriting the classes I am giving through props.
## Repro
`<MultiSelect
				options={['Food', 'Transport', 'Shopping', 'Entertainment', 'Health', 'Education']}
				allowUserOptions={true}
				id="expense-tags"
				outerDivClass="input input-bordered"
				placeholder="Select or create tags"
			/>` A simple tailwind code
Steps to reproduce the problem:
## Expected behavior
The input class should overwrite the multiselect classes but the :where is overwriting my class names resulting in class name - multiselect input input-bordered svelte-1r2hsto, screenshot attached
![image](https://github.com/janosh/svelte-multiselect/assets/45008879/5933ab57-48d3-46e2-8c3b-890f8381d154)

**Comment by AchalS-iglu** [comment]
nvm

**Comment by janosh** [comment]
Just for others coming here, the issue is with Svelte ([explained here](https://github.com/sveltejs/svelte/issues/4374#issuecomment-585789121)) and is difficult to work around without other tradeoffs.
