### ISSUE TITLE
Close dropdown after selecting option

### ISSUE THREAD

**Issue by jerefrer** [janosh/svelte-multiselect#264]
Hi there and thanks for this great component!

I'm trying to have the dropdown close after selecting an option, so that the user can see the results filtered just below. If it stays open then it's hard to see that, behind the dropdown, the results just got updated (being filtered using the option just selected).

![image](https://github.com/janosh/svelte-multiselect/assets/140954/ca5aa62c-0ffc-41cf-8dd7-26ccc47ebc7b)

I saw the option `focusInputOnSelect` and thought that, yay, I found the solution to my use case.
But even if I set it to `false`, the dropdown stays open even though the focus is not put back in the select.

Could we have either another option `closeDropdownOnSelect`, or just have `focusInputOnSelect` close the dropdown if set to `false` or `'desktop'` ?

I'm not sure I understand what could be the purpose of having `focusInputOnSelect` set to `false` if the dropdown stays open ...

It would be even greater if we could set a placeholder for the input even after options have been selected. Then why not have the placeholder be a `slot` instead of a `prop`, so that it could change dynamically. 

![image](https://github.com/janosh/svelte-multiselect/assets/140954/06b7efa5-af20-427e-9fc6-c3c23bcadbf1)

Thanks for reading 😉

**Comment by AchalS-iglu** [comment]
+1

**Comment by janosh** [comment]
If you set `maxSelect={1}`, the dropdown will always auto-close on select. Is that an option for you? Based on your screenshot, it sounds like you don't need more than one selection at a time? Although you seem to have an unusual setup where the `MultiSelect` selection is used to populate another list of options?

**Comment by AchalS-iglu** [comment]
I am not the person you're asking but I require multiple selections but I still want it to close on select.

**Comment by janosh** [comment]
Regarding your 2nd question about the placeholder slot, maybe the [`"after-input"`](https://github.com/janosh/svelte-multiselect#--slots) slot serves your purpose?

**Comment by janosh** [comment]
@AchalS-iglu Thanks, good to know! I'll whip something up.

**Comment by jerefrer** [comment]
Woohoo 🎉 

Thank you so much for those quick changes :)

However I'm still not exactly getting the perfect UX I had in mind.

I opened [a new issue](https://github.com/janosh/svelte-multiselect/issues/268) to try to discuss what I feel could be made even better.
