### ISSUE TITLE
Documentation Suggestion: div.multiselect overwrites .multiselect

### ISSUE THREAD

**Issue by Lemonsity** [janosh/svelte-multiselect#27]
Simply wish to notify something that I am unsure is by design or bug:

In the documentation, it is suggested for granular control, use `:global(.multiselect)` to modify the style of the top-level wrapper. However, as will be shown in the first screenshot, this does not seems to be working at the moment:
![Not Applied](https://user-images.githubusercontent.com/38927629/153986654-6c35ddbb-644e-4bb8-9d33-eff3d5092776.JPG)

There does seem to be a solution by selecting `:global(`**`div.multiselect`**`)` instead, as is shown here (Notice only the bottom border remains):
![Applied](https://user-images.githubusercontent.com/38927629/153986737-98b832b3-8e7d-4a39-9df7-f86f423a034c.JPG)

Apologies if this was intended that I just did not catch. 
Note this is not a major issue, can be solved by changing the documentation to provide guidance.

Thank you for developing this library, it is useful

**Comment by janosh** [comment]
Good catch. This is indeed an error in the readme. The `:global()` selectors listed there should work as documented. Fix incoming.
