### ISSUE TITLE
How to make added values only as string with allowUserOptions?

### ISSUE THREAD

**Issue by JustDenP** [janosh/svelte-multiselect#272]
@janosh Hello, I want to add in my selected array only string values, but with allowUserOptions, if a user adds a numeric, the value will be added as a number.

**Comment by janosh** [comment]
> if a user adds a numeric, the value will be added as a number.

Only if it's the first item in selected, right? This is a rare edge case. MultiSelect tries to infer what the type should be from the existing options.

> If `allowUserOptions` is `true` or `'append'` then the type `object | number | string` of entered value is determined by `typeof options[0]` (i.e. the first option in the dropdown list) to keep type homogeneity.

https://github.com/janosh/svelte-multiselect/blob/54963ec3a5053581244c41ad68db2d25ff31622f/readme.md#L117

If the user happens to start with a numeric value but you want strings, I'd recommend you just string-cast downstream from MultiSelect.

**Comment by JustDenP** [comment]
Okay, thank you for your answer, now I format my values in next functions, but I think it will be useful to have a prop to decide which type I want to store in a selected array

**Comment by janosh** [comment]
I agree. PR welcome!
