### ISSUE TITLE
Customizing user message <li>

### ISSUE THREAD

**Issue by acidMyke** [janosh/svelte-multiselect#273]
I'm using Tailwind to customize the MultiSelect component through [class props](https://multiselect.janosh.dev/#with-css-frameworks)

While successful in altering the appearance of the options, I encountered difficulty in applying changes specifically to the user message option. 

I'm wondering if it's feasible to introduce similar props for customizing user message, such as `liUserMsgClass` and `liUserMsgActiveClass`.

---
I can implement the changes and make a PR if you find this idea acceptable.

**Comment by janosh** [comment]
Sure, PR welcome.
