### ISSUE TITLE
Required doesn't reset when input has been invalidated

### ISSUE THREAD

**Issue by erezarnon** [janosh/svelte-multiselect#285]
If a multiselect is required and you submit a form, triggering the error, setting `required` to false doesn't work. It continues being required.

## Repro

```
<script>
  import MultiSelect from 'svelte-multiselect'
  import { colors } from './options'

  let required = true;
</script>


<form on:submit|preventDefault={() => {}}>
	<label>
		<input type="checkbox" bind:checked={required}>
		Is required
	</label>
	
	<MultiSelect
		options={[{foo:42}]}
		placeholder="Pick some colors..."
		{required}
	/>

	<button type="submit">Submit</button>
</form>
```

Steps to reproduce the problem:

1. Submit form
2. Uncheck `required`
3. Submit form again. Input is still required

**Comment by janosh** [comment]
thanks for reporting. fixed in [v10.3.0](https://www.npmjs.com/package/svelte-multiselect/v/10.3.0).
