### ISSUE TITLE
Options background not changing color in dark mode

### ISSUE THREAD

**Issue by imodrews** [janosh/svelte-multiselect#288]
Hi everyone, has anyone else had issues with the coloring in dark mode? For me, everything except the dropdown changes to dark mode when dark mode is enabled.

<img width="531" alt="Screenshot 2024-04-26 at 16 12 22" src="https://github.com/janosh/svelte-multiselect/assets/51444906/edebcde4-1f3a-4e2f-8403-8c1549c488d8">

 I am working with Tailwind CSS and have tried a lot of different things that aren't working. However, I don't understand why all the other parts change in dark mode and not the options. 
Any suggestions would be appreciated!

**Comment by Rostekip** [comment]
Try this :)
<MultiSelect ulOptionsClass = "dark:!bg-gray-800 !bg-gray-100"  bind:selected options={currencies} />

**Comment by imodrews** [comment]
This works! Thanks so much :)

**Comment by janosh** [comment]
if this is a CSS specificity issue, i'm hoping svelte 5 using `:where()` to lower specificity of default styles will solve this issue without needing to know @Rostekip's workaround (#281 #140).
