### ISSUE TITLE
Style option for token text

### ISSUE THREAD

**Issue by cabreraalex** [janosh/svelte-multiselect#3]
Hi, this component is great! Would it be possible to add an option to change the color of the token text? Looks like you can change the background, but I have a dark background and would like white text. 

More generally, would it be possible to pass in custom classes? Using tailwind, would be nice to use it to pass in class styles.

Thanks!

**Comment by janosh** [comment]
Thanks! Which parts of the component you think would most need a class prop in order to work well with Tailwind?

I've never used Tailwind myself. Is there a common/best practice for what class name props should be called?

Something like this?

```js
  export let outerDivClass = ``
  export let ulTokensClass = ``
  export let liTokenClass = ``
  export let ulOptionsClass = ``
  export let liOptionClass = ``
```

```html
<div class="multiselect {outerDivClass}"
  ...
  <ul class="tokens {ulTokensClass}">
    ...
```

**Comment by cabreraalex** [comment]
Hi sorry for not following up! I ended up using svelte-select as they have a multiselect option. That's basically what it looked like that let me style each property.

**Comment by janosh** [comment]
Cool, let me know if it works for you.
