### ISSUE TITLE
On website anchor links don't work.

### ISSUE THREAD

**Issue by frederikhors** [janosh/svelte-multiselect#31]
On website anchor links don't work. Windows 10, Chrome 98.

https://svelte-multiselect.netlify.app/#usage for example.

**Comment by janosh** [comment]
Thanks for catching this! The ToC broke 5 days ago due to a stupid mistake I made in https://github.com/janosh/svelte-toc/commit/f0b6f5fdd5240eae9cc66708e783717659d618bd. Should be fixed in latest deploy.

**Comment by frederikhors** [comment]
It works great now.
