### ISSUE TITLE
A new prop for `searchText`?

### ISSUE THREAD

**Issue by frederikhors** [janosh/svelte-multiselect#33]
I need a way to query options based on what `searchText` currently is. As the user is typing.

Can we use the DOM input element value?

Do we need a new prop to `bind`?

What are your thoughts on this?

**Comment by frederikhors** [comment]
And since we're talking about it, a debounce option for changing this text would be great.

Something like:

```ts
import { debounce } from "lodash-es";

const newSearchText = debounce((val) => (searchText = val), 1000);
```

I know I can do it, but having a prop like:

```ts
debounce={1000}
```

is unvaluable.

**Comment by janosh** [comment]
I agree it makes sense to expose the user-entered search text. And the open/close state of the options dropdown as well, while we're at it:

```diff
+ export let searchText = ``
+ export let showOptions = false
```

Just to be clear re debouncing, you want to prevent the user from updating the value several times a second while he's typing?

**Comment by frederikhors** [comment]
> you want to prevent the user from updating the value several times a second while he's typing?

Yep. Just so as not to clog the server with requests.

**Comment by janosh** [comment]
I think it that case it makes more sense to debounce your requests rather than the prop, no? Would that a problem for some reason?

I'm a bit worried about UX suffering from it being less snappy for devs not doing server requests with it (which I assume would be the majority).

**Comment by frederikhors** [comment]
Yeah. You're right. Not something to debounce in SMS.
