### ISSUE TITLE
Is there a way (a prop?) to change the message if nothing is found?

### ISSUE THREAD

**Issue by frederikhors** [janosh/svelte-multiselect#34]
Is there a way (a prop?) to change the message if nothing is found?

**Comment by janosh** [comment]
There is the `noOptionsMsg = 'No matching options'` prop. Does that serve your purpose?

**Comment by frederikhors** [comment]
Oh wow. Is not on docs. Sorry. Should we add it?

**Comment by janosh** [comment]
Oops, I must have forgotten to add that.
