### ISSUE TITLE
Is there a prop to change class for current active `li`?

### ISSUE THREAD

**Issue by frederikhors** [janosh/svelte-multiselect#35]
Is there a prop to change class for current active `li`?

I would like to use `background-color: blue` when on hover.

I don't find any prop for this, am I wrong?

**Comment by janosh** [comment]
There is now:

```svelte
export let liActiveOptionClass = ``
```

Related https://github.com/sveltejs/svelte/issues/7294.

**Comment by janosh** [comment]
@frederikhors Just occurred to me, do you think we need a class for the `<input>` itself. Right now we have these:

```svelte
<div class="multiselect {outerDivClass}">
  <ul class="selected {ulSelectedClass}">
    <li class={liSelectedClass}>Selected 1</li>
    <li class={liSelectedClass}>Selected 2</li>
  </ul>
  <input />  // add inputClass here?
  <ul class="options {ulOptionsClass}">
    <li class={liOptionClass}>Option 1</li>
    <li class="{liOptionClass} {liActiveOptionClass}">
      Option 2 (currently active)
    </li>
  </ul>
</div>
```
Unless I misunderstand the capabilities of something like TailwindCSS, this does not allow to e.g. change the color of the `input::placeholder`, correct?

**Comment by frederikhors** [comment]
I'm unable to try now (busy). I'm using svelte-select for now. I'll switch in the future. I think tailwind does this thing: https://tailwindcss.com/docs/hover-focus-and-other-states#placeholder-text.

**Comment by janosh** [comment]
Thanks for the link. 👍 

That does look like a class on the `<input>` is needed. I'll add one.
