### ISSUE TITLE
Shadow on the list?

### ISSUE THREAD

**Issue by frederikhors** [janosh/svelte-multiselect#36]
Maybe we need some "shadow" for the list which could blend in with the page when it is open if it is of the same color.

**Comment by janosh** [comment]
I'm a bit ambivalent on this question. If we add a `box-shadow` to the default dropdown list styles, I think it should be a subtle one. Some people prefer their site design to be flat. Maybe this?

```css
box-shadow: var(--sms-options-shadow, 0 0 14pt -8pt black);
```
