### ISSUE TITLE
Change the UX a bit if we are in single mode

### ISSUE THREAD

**Issue by frederikhors** [janosh/svelte-multiselect#37]
If we are in "single" mode I think we can remove the "external X" at all.

Or maybe we can remove (or change a little) the UI for the single mode and remove the "tag" x.

I don't know, but both together is strange.

And even the `1/1`. I know we can remove it with `maxSelectMsg={() => ""}` but maybe is unnecessary.

**Comment by janosh** [comment]
> I don't know, but both together is strange.

Agreed. I think removing the outer "remove all" button in single mode is easier but maybe removing the "tag" cross icon looks better. Need to think about it.

> And even the `1/1`. I know we can remove it with `maxSelectMsg={() => ""}` but maybe is unnecessary.

Good point, will do that tomorrow.

**Comment by frederikhors** [comment]
Something like this for inspiration:

https://vue-select.org/
