### ISSUE TITLE
Is there a way to avoid to use `!important` CSS mode?

### ISSUE THREAD

**Issue by frederikhors** [janosh/svelte-multiselect#38]
Is there a way to avoid to use `!important` CSS mode?

Can we move `outerDivClass` to the end?

I need my css classes to override yours.

Am I wrong?

![image](https://user-images.githubusercontent.com/41120635/154818270-c13b4e4d-2c65-4b75-b212-aa5d46e41930.png)

**Comment by janosh** [comment]
Could you clarify? `outerDivClass` already comes after class `multiselect`. Or do you mean after _all_ other classes?

```diff
<div
- class="multiselect {outerDivClass}"
  class:readonly
  class:single={maxSelect == 1}
  class:open={showOptions}
+ class="multiselect {outerDivClass}"
  on:mouseup|stopPropagation={() => setOptionsVisible(true)}
  use:onClickOutside={() => setOptionsVisible(false)}
  use:onClickOutside={() => dispatch(`blur`)}
>
```

**Comment by frederikhors** [comment]
I mean after all others.

**Comment by janosh** [comment]
I just noticed that Svelte always applies the conditional classes last, no matter in what order I specify them. So now I'm not sure if this issue is actually solved and if not, how it can be solved.

```svelte
  <MultiSelect
    id="fav-web-tool"
    options={webFrameworks}
    bind:selectedLabels={selectedWeb}
    bind:activeOption={activeWeb}
    maxSelect={6}
    {placeholder}
    {filterFunc}
    liActiveOptionClass="foobar"
  />
```

![Screen Shot 2022-02-19 at 21 34 41](https://user-images.githubusercontent.com/30958850/154819904-7925d21b-d1d6-4861-80e9-482486bb8e31.png)

@frederikhors Will release a new version tomorrow. Perhaps you can let me know if this problem persists.

**Comment by frederikhors** [comment]
Ok. I'll try ASAP.

**Comment by frederikhors** [comment]
Pleas re-open it.

**Comment by janosh** [comment]
I just released [v3.3.0](https://github.com/janosh/svelte-multiselect/releases/tag/v3.3.0) with all the changes we discussed. Let me know how it works for you.

**Comment by frederikhors** [comment]
I will try in a few hours.

**Comment by frederikhors** [comment]
I tried with the `4.0.0`. This is still an issue.

**Comment by egdegauperaa** [comment]
@frederikhors doesn't it work to be more specific in the css, for instance adding a class in your statements that is outside the svelte component?

**Comment by frederikhors** [comment]
Yep maybe. But I need to try, and I cannot right now.

**Comment by janosh** [comment]
@frederikhors Have you had a chance to try @egdegauperaa's suggestion? If so does it help?

**Comment by frederikhors** [comment]
We can close. I don't have time right now. I'll re-open if this is still an issue. Thanks both.
