### ISSUE TITLE
get values from  foreach

### ISSUE THREAD

**Issue by Avi-ADAM** [janosh/svelte-multiselect#4]
i'm working with svelte-multiselect alot and its beautiful and enjoying.
now i need multi select for a loop showing an array like // {#each miData as data, i} // so every line there have a an multi select input, now with the text input i use // bind:value={data.spnot} // and it work fine but with the multiselect its not working, any ideas? thank alot!

**Comment by Avi-ADAM** [comment]
i use // bind:selected={data.selected1} // and it worked

**Comment by janosh** [comment]
Hi there, glad you like Svelte Multiselect.￼

I actually considered renaming `bind:selected` to `bind:value` but haven't made up my mind yet. What do you prefer?￼

**Comment by Avi-ADAM** [comment]
sure its so beautiful and works perfect, i think bind:selected is good
