### ISSUE TITLE
Loading indicator is broken

### ISSUE THREAD

**Issue by frederikhors** [janosh/svelte-multiselect#43]
I'm trying again s-ms.

I think the loading indicator is broken:

![issue](https://user-images.githubusercontent.com/41120635/155133150-81f33c3a-efe3-48b3-a91a-0b3c7a2dd85d.gif)

**Comment by janosh** [comment]
Which browser is that? For me it looks like this in Chrome, Brave and Safari.

https://user-images.githubusercontent.com/30958850/155133998-49d92c12-65fe-49fc-a35b-461d449904a4.mp4

**Comment by frederikhors** [comment]
I'm using Chrome 98 on Windows 10.

I'm using Tailwind. Nothing more.

**Comment by frederikhors** [comment]
No manual css classes.

**Comment by frederikhors** [comment]
It would be amazing if I can use a custom loading spinner component.

**Comment by frederikhors** [comment]
I think you should close the loading indicator in another `<div>`.

**Comment by janosh** [comment]
@frederikhors [You can already](https://github.com/janosh/svelte-multiselect#slots):

> MultiSelect.svelte has 3 named slots:
> ...
> - `slot="spinner"`: Custom spinner component to display when in `loading` state. Receives no props.

**Comment by frederikhors** [comment]
> > It would be amazing if I can use a custom loading spinner component.
> 
> @frederikhors [You can already](https://github.com/janosh/svelte-multiselect#slots). From the readme:
> 
> > MultiSelect.svelte has 3 named slots:
> > ...
> > 
> > * `slot="spinner"`: Custom spinner component to display when in `loading` state. Receives no props.

It works. Thanks.

**Comment by frederikhors** [comment]
> I think you should close the loading indicator in another `<div>`.

@janosh I found the problem.

**Comment by janosh** [comment]
@frederikhors Can this issue be closed? You mentioned you found the problem (though not sure what you mean) and @kleinicke reported privately that the loading spinner renders fine for him in Edge on Windows.
