### ISSUE TITLE
What about `isLoading` instead of `loading`?

### ISSUE THREAD

**Issue by frederikhors** [janosh/svelte-multiselect#46]
What about `isLoading` instead of `loading`?

**Comment by janosh** [comment]
I went with the [vue-select API](https://vue-select.org/api/props.html#loading) here where they also called it `loading`. What's your reason for preferring `isLoading`? Make it clearer it's a boolean?

**Comment by frederikhors** [comment]
> Make it clearer it's a boolean?

Exactly that.

**Comment by janosh** [comment]
Will consider it.

**Comment by janosh** [comment]
I decided against renaming to `isLoading` to avoid another breaking change and since `loading` is a bit more flexible for future API changes in case we ever need the prop to be more than just a boolean. Thanks for the suggestion though.
