### ISSUE TITLE
HasError prop?

### ISSUE THREAD

**Issue by frederikhors** [janosh/svelte-multiselect#47]
I think we need an `hasError` prop.

For the same reason we have an `isLoading` (or `loading`) one.

**Comment by janosh** [comment]
Could you be a bit more specific here. The `loading` prop is controlled entirely externally.

I assume `hasError` should, by contrast, be handled by the component itself (i.e. if user tries to submit and `required=true` but `selected` is empty, `hasError` should automatically be set to `true`?) but also allow for external control?

**Comment by janosh** [comment]
The new prop is now called `invalid` and [documented in the readme](https://github.com/janosh/svelte-multiselect#props). Thanks for this suggestion!
