### ISSUE TITLE
Unit test failed when component has svelte-multiselect

### ISSUE THREAD

**Issue by davipon** [janosh/svelte-multiselect#48]
Hi @janosh, I like to thank you for creating such a great component! I love it!

Everything works great so far (v4.0.0) in my svelte app until I tried to add some unit tests.
Test failed when I tested component which has svelte-multiselect, Jest threw error (Vitest broke right away) like this:
<img width="1206" alt="Screen Shot 2022-02-26 at 12 45 38 PM" src="https://user-images.githubusercontent.com/7219045/155829414-3603b0a5-287b-4939-9f91-d1f2db5adb4b.png">

I'd already setup transformers so it's not a ESM problem in Jest, and other tests passed with different svelte libraries.

Here is a reproducible repo that you can check: https://github.com/davipon/test-failed
I simply import [svelte-tiny-virtual-list](https://github.com/Skayo/svelte-tiny-virtual-list) & svelte-multiselect in the same test file and try to render them.
Test would fail before rendering Multiselect:
```
test('render multiselect', () => {
  render(Multiselect, { options: webFrameworks });
});
```
I'm not familiar with creating Svelte package, but I found a difference in these two libraries' `index.js`:
svelte-tiny-virtual-list:
<img width="694" alt="Screen Shot 2022-02-26 at 1 02 41 PM" src="https://user-images.githubusercontent.com/7219045/155829924-4bb965d0-fe88-4893-8635-271a12a13052.png">

svelte-multiselect:
<img width="422" alt="Screen Shot 2022-02-26 at 1 04 51 PM" src="https://user-images.githubusercontent.com/7219045/155829946-29779add-412e-48bd-847f-c239e9ef2a8c.png">

Not sure if information above can help, and thanks again for your hard work!

**Comment by janosh** [comment]
@davipon Thanks for the detailed analysis! The error is a bit odd though. I have some local `vitest`s that aren't quite ready to be pushed yet but those run fine whether I import from the component file or from `index.(j|t)s`.

```ts
// tests/multiselect.test.ts
import { tick } from 'svelte'
import { expect, test } from 'vitest'

// all of these work for me
import MultiSelect from '../src/lib/MultiSelect.svelte'
import MultiSelect from '../src/lib'
import MultiSelect from '../package/index'
import MultiSelect from '../package/MultiSelect.svelte'

test(`mount component`, async () => {
  const options = [`Banana`, `Watermelon`, `Apple`, `Dates`, `Mango`]
  const instance = new MultiSelect({
    target: document.body,
    props: { options },
  })
  expect(instance).toBeTruthy()

  const lis = document.body.querySelectorAll(
    `div.multiselect > ul.options > li`
  )
  expect(lis.length).toEqual(5)
  lis.forEach((li, i) => {
    expect(li.textContent).toContain(options[i])
  })
})
```

This is my `vite.config.ts`:

```ts
import { svelte } from '@sveltejs/vite-plugin-svelte'

export default {
  plugins: [svelte({ hot: !process.env.VITEST })],
  test: {
    environment: `jsdom`,
  },
}
```

I'm happy to change

```diff
- export { default } from './MultiSelect.svelte'
+ export { default as default } from './MultiSelect.svelte'
```

if that's necessary. Could you do me a favor and actually go into `node_modules/svelte-multiselect/index.js` and make this change to see if it really solves your problem? I'd also like to find out why your and my `vitest` seem to behave differently.

**Comment by davipon** [comment]
Thanks @janosh, it works after adding `transformIgnorePatterns` in jest.config.json:
```json
{
  "testEnvironment": "jsdom",
  "transformIgnorePatterns": ["node_modules/?!(svelte-multiselect)"],
  "transform": {
    "^.+\\.[t|j]s?$": "esbuild-jest",
    "^.+\\.svelte$": ["svelte-jester", { "preprocess": true }]
  }
}

```
While test still failed in Vitest, I couldn't find the corresponding config in Vitest so far, will raise a ticket there.
***
Since SvelteKit wouldn't build code when packaging, also transformers like babel-jest, ts-jest, svelte-jester wouldn't transpile files within `node_modules`, this seems to be a general problem for future Svelte ecosystem when it comes to unit testing.

I think it would be great if we can add a section in README for people who will encounter the same problem, like recommended Jest config for unit testing, can also add Vitest config if there is a solution in the future.
I can create a PR for that if you think it's OK. Thanks again for your time!

**Comment by janosh** [comment]
> While test still failed in Vitest, I couldn't find the corresponding config in Vitest so far, will raise a ticket there.

Thanks. Could you link this issue over there? I'd like to subscribe to your `vitest` issue.

> this seems to be a general problem for future Svelte ecosystem when it comes to unit testing.

Indeed which is why I'm very curious to hear if there's a recommended solution.

> I can create a PR for that if you think it's OK.

Sure that would be great!

**Comment by janosh** [comment]
Based on https://github.com/vitest-dev/vitest/issues/809, https://vitest.dev/config/#transformmode might be something to play around with.

**Comment by davipon** [comment]
I also tried `transformmode` but it failed as well.

Anyway, I asked in Vitest Discord channel and got the answer!
We need to use `dep.inline` in Vitest:
```
test: {
  globals: true,
  environment: 'happy-dom',
  deps: {
    inline: [/svelte-multiselect/]
  }
}
```
Now we know how to deal with errors when unit testing most of the Svelte component packages (I believe) in both Jest and Vitest, I'll create a PR to add a **Unit Test** section in README with examples.

Thanks again @janosh, your comments really helped me to dig in and find the root cause, please kindly close this issue, have a good one!

**Comment by janosh** [comment]
Cool! Let's close this issue once your PR to update the readme is merged.
