### ISSUE TITLE
selected.length Property Cause Issue

### ISSUE THREAD

**Issue by Lemonsity** [janosh/svelte-multiselect#49]
Hi, there seem to be some issue with the binding `selected` property

Although supposedly the value should be an array, accessing the `.length` property will break the page.

It can be demonstrated by using this code as `App.svelte`:
```js
<script>
  import MultiSelect from "svelte-multiselect";

  const data = [
    {label: "alpha", value: "a"}, 
    {label: "bravo", value: "b"}, 
    {lable: "charlie", value: "c"},
  ];

	let selected;
</script>

<main>
  <MultiSelect bind:selected options={data} placeholder="Search for tags" />
  <p>{selected.length}</p>
</main>
```

We can confirm it is the `.length` that broke the page because if replace `selected.length` with `JSON.stringify(selected)`, we can then see that data is added.

A similar issue occurs when trying to access an value of `selected` (like `selected[0]`). 

Personally, I think this is a rather big issue, since its behaviour is unpredictable.

**PS**: Using the code also reveals another issue, that the "charlie" option becomes undefined in the drop-down menu. I am not sure if I should open a different issue for that. Sorry I could not identify the cause of the issue and fix it.

**Comment by janosh** [comment]
@Lemonsity Thanks for the bug report. Will diagnose this now. There is a much simpler workaround for the time being though: use optional chaining. `selected?.length` should cause you no trouble.

**Comment by janosh** [comment]
The problem also disappears if you declare `let selected = [];` instead of `let selected;`. The 2nd is equivalent to `let selected = undefined;`. Not sure this component can do anything about `selected` not having a `length` property on first render in that case.

**Comment by janosh** [comment]
> PS: Using the code also reveals another issue, that the "charlie" option becomes undefined in the drop-down menu. I am not sure if I should open a different issue for that. Sorry I could not identify the cause of the issue and fix it.

That's because you have a typo:

```diff
  const data = [
    {label: "alpha", value: "a"}, 
    {label: "bravo", value: "b"}, 
-   {lable: "charlie", value: "c"},
+   {label: "charlie", value: "c"},
  ];
```

**Comment by Lemonsity** [comment]
Hi Janosh, 

Thanks a lot for the help. Can confirm both **optional chaining** and **initializing the value** are valid solutions as of now. I would however recommend initializing with an empty array, as you can do `selected[index]` that way.
