### ISSUE TITLE
event hendle

### ISSUE THREAD

**Issue by Avi-ADAM** [janosh/svelte-multiselect#5]
hallo
i want to have a function running any time the value is changes, i tried different things like on:change={function} and on:selected={function} non seems to work.
 thanks and thanks for these amazing multiselect

**Comment by janosh** [comment]
This definitely needs to be better documented. MultiSelect dispatches 3 different types of events:

- `on:add={(event) => console.log(event.detail.token)}`: triggers when a new token is selected
- `on:remove={(event) => console.log(event.detail.token)}`: triggers when a selected token is removed
- `on:blur={yourFunctionHere}`: triggers when the input field looses focus

Will add a section to the readme as well as a new event `on:change` that triggers for both `add` and `remove`.

**Comment by janosh** [comment]
[Published in v1.1.10](https://www.npmjs.com/package/svelte-multiselect/v/1.1.10).
