### ISSUE TITLE
Close list when losing focus

### ISSUE THREAD

**Issue by egdegauperaa** [janosh/svelte-multiselect#53]
When using the keyboard to navigate, the list opens automatically when the component receives focus. It doesn't however close when losing focus. Would that be possible to implement, or have a prop to enable it?

To reproduce what I'm describing:
https://svelte-multiselect.netlify.app/
Use tab to navigate to the first list
When it opens use tab to jump to the next list (or other item if this had been a typical form)
The second list opens but the first one stays open.

**Comment by janosh** [comment]
Good catch! Closing on blur should definitely be the default behavior. No new prop needed I think.

**Comment by janosh** [comment]
Fix released in v4.0.1.
