### ISSUE TITLE
Better a11y

### ISSUE THREAD

**Issue by egdegauperaa** [janosh/svelte-multiselect#56]
I suggest adding aria-disabled equal to true to <input> when the disabled prop has been used (true). Not to replace that the "disabled" attribute that we already have (thanks!), but to additionaly inform screen readers.

From [mdn](https://developer.mozilla.org/en-US/docs/Web/Accessibility/ARIA/Attributes/aria-disabled):

"The aria-disabled attribute is similar to the HTML disabled attribute, but better. The first rule of ARIA is "If you can use a native HTML element or attribute with the semantics and behavior you require already built in, instead of repurposing an element and adding an ARIA role, state or property to make it accessible, then do so." aria-disabled is an exception to that rule. It is one of the only cases where an ARIA attribute may be better than the native disabled attribute HTML equivalent.

**Comment by janosh** [comment]
@egdegauperaa Yeah, I made that change locally already, wanted to push yesterday but didn't have the time. Will do tonight hopefully.

I guess we can also add `aria-invalid` to this issue and make it about better a11y in general.

**Comment by janosh** [comment]
We should also add [`aria-expanded`](https://developer.mozilla.org/en-US/docs/Web/Accessibility/ARIA/Attributes/aria-expanded) when the dropdown is open.

**Comment by egdegauperaa** [comment]
Yes, I think so too.
