### ISSUE TITLE
Fix options conversion

### ISSUE THREAD

**Issue by GodPingu** [janosh/svelte-multiselect#65]
Options is currently mapped to _options to convert "raw" options to objects with label/value for objects it uses this check 
`if (!op.value)
     op.value = op.label;
`
to check for ops without values however this is incorrectly flagged on a value of 0 I'd suggest the check is changed to `if(op.value == undefined)`

**Comment by janosh** [comment]
@GodPingu Thanks for reporting! Will be fixed in the next release.
