### ISSUE TITLE
on:change not called if all elements removed

### ISSUE THREAD

**Issue by Primdahl26** [janosh/svelte-multiselect#7]
Hello!

My issue is that when you choose to remove all items from the Muliti-select, the `on:change` is not called. 

I will give you an example.

```svelte
<MultiSelect
    bind:selected={selectedGenres}
    on:change={debounceInput}
    options={genres}
    placeholder="Select genres..."
/>
```
When I remove 1 element at a time `on:change` is called fine, but as soon as I remove all elements it will not be called. 

![image](https://user-images.githubusercontent.com/50198099/131978478-86524e99-c89c-4728-9b7d-743406db1aa8.png)

Am I doing something wrong? :)

Best regards

**Comment by janosh** [comment]
@Primdahl26 Good catch! Should be fixed in v1.1.11.
