### ISSUE TITLE
Unknown file extension Error & SSR

### ISSUE THREAD

**Issue by otprocta** [janosh/svelte-multiselect#77]
![Screen Shot 2022-04-22 at 9 11 01 AM](https://user-images.githubusercontent.com/104103710/164646566-4be336b7-06b6-46ed-afe7-287868f210d7.png)

I don't know how to resolve these errors....
<img width="1533" alt="Screen Shot 2022-04-22 at 10 01 35 AM" src="https://user-images.githubusercontent.com/104103710/164673872-cf7709fd-66d5-4565-8c72-87674c43f4ee.png">

**Comment by otprocta** [comment]
i am using multi-select with sveltekit

**Comment by janosh** [comment]
Do you have a link to your repo? If private, could you share your versions (of SvelteKit + MultiSelect) and how you import?

**Comment by otprocta** [comment]
Private repo *  -I import like so => import MultiSelect from 'svelte-multiselect'


 "devDependencies": {
 
    "@sveltejs/adapter-auto": "next",
    "@sveltejs/kit": "next",
    "svelte": "^3.47.0",
    "svelte-multiselect": "^4.0.6",
    "tailwindcss": "^3.0.24"
  },

**Comment by otprocta** [comment]
usage =>   `<MultiSelect bind:selected={selectedUsers} options={users} loading={loadingUsers} />`

or inside the Svelte-Drawer component *-an external dev dependency

```
<Drawer>
    <MultiSelect bind:selected={selectedUsers} options={users} loading={loadingUsers} />
     <MultiSelect bind:selected={selectedLabels} options={labels} loading={loadingLabels} />
<Drawer/>
```

**Comment by janosh** [comment]
Could you check your lock file and make sure `vite` is installed? Or try adding it as a dev dep explicitly.

**Comment by otprocta** [comment]
exists in lock file - i will also try adding it as a dev dep.

**Comment by janosh** [comment]
Then maybe adding a `"main": "index.js"` to `package.json` on my end could help. Though I've never understood when or why that's needed. Could you go into `node_modules/svelte-multiselect/package.json` and insert `"main": "index.js"` below `"svelte": "index.js"`, then restart dev server and check if error disappears?

**Comment by otprocta** [comment]
doing [this](https://github.com/janosh/svelte-multiselect/issues/77#issuecomment-1106256411) removed the error. thanks.
