### ISSUE TITLE
Infer more precise types for `bind:selected` and `let:option`

### ISSUE THREAD

**Issue by janosh** [janosh/svelte-multiselect#78]
Figure out if generics (or anything) can be used to infer the type of `bind:selected` and `let:option` in slot components correctly from type of `options` prop. See https://github.com/sveltejs/language-tools/issues/442#issuecomment-726377055 for related question.

**Comment by janosh** [comment]
Goal is to fix type errors like this:

![Screen Shot 2022-04-22 at 12 15 02](https://user-images.githubusercontent.com/30958850/164721555-31ec0500-4606-4742-98ff-efd9a4d373cc.png)

**Comment by Michael-Reich** [comment]
Yes, this would help a lot!

**Comment by joelmukuthu** [comment]
@janosh I'm up for helping with this, just checking to see if perhaps you're already working on it. Let me know if you'd like a PR for this :)

**Comment by janosh** [comment]
@joelmukuthu Yes, a PR that fixes this would be amazing. 👍 

I have no working branch for this yet so feel free to start fresh from `main`.
