### ISSUE TITLE
Error using svelte-multiselect in Svelte REPL

### ISSUE THREAD

**Issue by otprocta** [janosh/svelte-multiselect#80]
Svelte-MultiSelect no longer works in the Svelte [REPL](https://svelte.dev/repl/ea202bd627134d898802a11cfaf8ff0e?version=3.47.0).

<img width="912" alt="Screen Shot 2022-04-27 at 12 41 50 AM" src="https://user-images.githubusercontent.com/104103710/165410174-3aa9bd32-a8ad-4c83-a87a-690c7bb28754.png">

**Comment by janosh** [comment]
@otprocta Thanks for reporting. Looks like something went wrong in the transition from v4 to v5. Just looked in the package folder at generated files. `MultiSelect.svelte` now has a weird remnant from a type import line

```js
import './';
```

that used to be removed entirely. Not sure if that's the cause for this error. Need to investigate more. As a short-term fix, you can append package version numbers onto NPM imports. [You're error disappears](https://svelte.dev/repl/4279890dae0942caa860e74f2e7a8a6f) if you use the latest v4 release:

```diff
-  import MultiSelect from 'svelte-multiselect'
+  import MultiSelect from 'svelte-multiselect@4.0.6'
```

**Comment by janosh** [comment]
Unfortunately these errors are hard to troubleshoot in the REPL due to lack of stack trace (outstanding issue https://github.com/sveltejs/sites/issues/173) and I can't reproduce locally.

**Comment by janosh** [comment]
@otprocta Small update: [this might be an issue with the Svelte REPL](https://github.com/sveltejs/sites/issues/354#issuecomment-1167586335) and not with MultiSelect. Follow https://github.com/sveltejs/sites/issues/354 for further developments.

**Comment by janosh** [comment]
Just noticed that this issue was fixed upstream. [Svelte REPL](https://svelte.dev/repl/a5a14b8f15d64cb083b567292480db05?version=3.52.0) now successfully deploys the latest version 7.1.0 of Multiselect.
