### ISSUE TITLE
`li.scrollIntoViewIfNeeded is not a function` error in console during keyboard navigation

### ISSUE THREAD

**Issue by abhijit-hota** [janosh/svelte-multiselect#87]
I'm getting the said error whenever I navigate (up/down) via keyboard.

![image](https://user-images.githubusercontent.com/8116174/175805282-b2494b1c-90cb-498f-a506-a2975b4ef50e.png)

**Comment by janosh** [comment]
What browser are you using?

**Comment by janosh** [comment]
Taking a look at https://caniuse.com/scrollintoviewifneeded, you're probably using Firefox? I knew [`scrollIntoViewIfNeeded`](https://developer.mozilla.org/en-US/docs/Web/API/Element/scrollIntoViewIfNeeded) was never standardized but I didn't know Firefox doesn't support it at all.

Just did a bit of testing and seems like `scrollIntoView` works just as well as `scrollIntoViewIfNeeded` so I'll switch to that.

**Comment by janosh** [comment]
Released as [v5.0.2](https://www.npmjs.com/package/svelte-multiselect/v/5.0.2).
