### ISSUE TITLE
`await tick` instead of `setTimeout`

### ISSUE THREAD

**Issue by ambiguous48** [janosh/svelte-multiselect#96]
I was digging through the source code and came across [this todo](https://github.com/janosh/svelte-multiselect/blob/13c26cacf53c19dcc777602b1a44ae6bb8dd2498/src/lib/MultiSelect.svelte#L243). Perhaps we can use [tick](https://svelte.dev/tutorial/tick) instead?

**Comment by janosh** [comment]
`await tick()` is what I tried originally (see https://github.com/janosh/svelte-multiselect/commit/c8f87660908f9f3335ed17b16d7c2c42c2a3eb79#diff-7d86c55b55f23806b2be4051d790e7c775fd5fa4e1ad3fc2da59eb51ce25c0e9L221) but it didn't work. Not sure why. If you have any clues, definitely interested to hear them.

**Comment by ambiguous48** [comment]
Not entirely sure to be honest. In the much simpler component that I was playing around with, `tick` managed to do the job. Although my component is pretty basic compared to yours, and has far less event listeners. One way to debug this might be to remove the unrelated event listeners in hopes of isolating the issue.

**Comment by janosh** [comment]
Thanks, good suggestion. I'm oressed for time atm but if anyone wants to investigate, I'm happy to support.

**Comment by janosh** [comment]
The component started using `await tick()` in 
https://github.com/janosh/svelte-multiselect/blob/fd8b37782cd508aacfc8125c6647cefe56144b80/src/lib/MultiSelect.svelte#L264
